In [1]:
import polars as pl
import pandas as pd
import numpy as np
import datetime as dt
import os
import sys
import json 
import importlib

sys.path.append("../utils/")

import helpers as hp

In [2]:
rng = np.random.default_rng(seed=274)

In [3]:

with open("../configs/zone_distances.json", "r") as json_file:
    zone_distances = json.load(json_file)

In [4]:
zone_distances

{'Yerbabuena': {'centroids': [20.964404421308334, -101.2847459818324],
  'points': [{'point': [20.9743, -101.300626],
    'distance': 0.01871089133756122},
   {'point': [20.946278, -101.298483], 'distance': 0.022743632462390598},
   {'point': [20.951706, -101.264939], 'distance': 0.023527992541503697},
   {'point': [20.979447, -101.274624], 'distance': 0.018131014585796808},
   {'point': [20.985938, -101.285636], 'distance': 0.02155196379935847},
   {'point': [20.9743, -101.300626], 'distance': 0.01871089133756122}]},
 'Marfil': {'centroids': [20.998877268148007, -101.29015919031652],
  'points': [{'point': [20.979212, -101.292779],
    'distance': 0.019839006379117525},
   {'point': [20.991242, -101.304647], 'distance': 0.016376628136369357},
   {'point': [21.006043, -101.294156], 'distance': 0.008205010702043177},
   {'point': [21.019272, -101.283363], 'distance': 0.021497285645706604},
   {'point': [21.008196, -101.275124], 'distance': 0.017688858391175503},
   {'point': [20.999863, -101.28527], 'distance': 0.004987569471714025},
   {'point': [20.98935, -101.285501], 'distance': 0.010605073096820709},
   {'point': [20.979212, -101.292779], 'distance': 0.019839006379117525}]},
 'Guanajuato': {'centroids': [21.017579148201516, -101.25657125727841],
  'points': [{'point': [21.001685, -101.236267],
    'distance': 0.025785399176272965},
   {'point': [21.004701, -101.25431], 'distance': 0.01307516675149282},
   {'point': [21.00885, -101.274008], 'distance': 0.01949969294791135},
   {'point': [21.023665, -101.277944], 'distance': 0.022222324890898416},
   {'point': [21.03464, -101.259223], 'distance': 0.017265700204490565},
   {'point': [21.026755, -101.241643], 'distance': 0.017522817170713547},
   {'point': [21.001685, -101.236267], 'distance': 0.025785399176272965}]}}

In [5]:
gym_hours = {"open" : 6,
             "close" : 22}

profiles = {
"1": {
"name" : "frequent_morning",
"days_probability" : {"mon": {"day_number" : 1, "day_name" : "Monday", "day_weight" : .89},
                      "tue": {"day_number" : 2, "day_name" : "Tuesday", "day_weight" : .76},
                      "wed": {"day_number" : 3, "day_name" : "Wednesday", "day_weight" : .85},
                      "thu": {"day_number" : 4, "day_name" : "Thursday", "day_weight" : .7},
                      "fri": {"day_number" : 5, "day_name" : "Friday", "day_weight" :.9},
                      "sat": {"day_number" : 6, "day_name" : "Saturday", "day_weight" : .9},
                      "sun": {"day_number" : 7, "day_name" : "Sunday", "day_weight" : 0}
},
"hour_mean" : 6.43,
"hour_std" : .75,
"plan_probability" : {"1": 0.05, "2": 0.2, "3" : 0.45, "4": 0.3}
},
"2" : {
"name" : "frequent_noon",
"days_probability" : {"mon": {"day_number" : 1, "day_name" : "Monday", "day_weight" : .7},
                      "tue": {"day_number" : 2, "day_name" : "Tuesday", "day_weight" : .82},
                      "wed": {"day_number" : 3, "day_name" : "Wednesday", "day_weight" : .67},
                      "thu": {"day_number" : 4, "day_name" : "Thursday", "day_weight" : .87},
                      "fri": {"day_number" : 5, "day_name" : "Friday", "day_weight" :.78},
                      "sat": {"day_number" : 6, "day_name" : "Saturday", "day_weight" : .84},
                      "sun": {"day_number" : 7, "day_name" : "Sunday", "day_weight" : 0}
},
"hour_mean" : 13.16,
"hour_std" : 1.40,
"plan_probability" : {"1": .2, "2": 0.5, "3" : 0.25, "4": 0.05}
            },
"3" :{
"name" : "frequent_night",
"days_probability" : {"mon": {"day_number" : 1, "day_name" : "Monday", "day_weight" : .74},
                      "tue": {"day_number" : 2, "day_name" : "Tuesday", "day_weight" : .87},
                      "wed": {"day_number" : 3, "day_name" : "Wednesday", "day_weight" : .76},
                      "thu": {"day_number" : 4, "day_name" : "Thursday", "day_weight" : .84},
                      "fri": {"day_number" : 5, "day_name" : "Friday", "day_weight" :.4},
                      "sat": {"day_number" : 6, "day_name" : "Saturday", "day_weight" : .8},
                      "sun": {"day_number" : 7, "day_name" : "Sunday", "day_weight" : 0}
},
"hour_mean" : 19.5,
"hour_std" : 1.15,
"plan_probability" : {"1": 0.15, "2": 0.15, "3" : 0.45, "4": 0.25}
},
"4" :{
"name" : "random_morning",
"days_probability" : {"mon": {"day_number" : 1, "day_name" : "Monday", "day_weight" : .4},
                      "tue": {"day_number" : 2, "day_name" : "Tuesday", "day_weight" : .4},
                      "wed": {"day_number" : 3, "day_name" : "Wednesday", "day_weight" : .3},
                      "thu": {"day_number" : 4, "day_name" : "Thursday", "day_weight" : 0.5},
                      "fri": {"day_number" : 5, "day_name" : "Friday", "day_weight" : .6},
                      "sat": {"day_number" : 6, "day_name" : "Saturday", "day_weight" : 1},
                      "sun": {"day_number" : 7, "day_name" : "Sunday", "day_weight" : 0}
},
"hour_mean" : 8.5,
"hour_std" : 2.05,
"plan_probability" : {"1": 0.65, "2": 0.25, "3" : 0.1, "4": 0}
},
"5" :{
"name" : "random_night",
"days_probability" : {"mon": {"day_number" : 1, "day_name" : "Monday", "day_weight" : .3},
                      "tue": {"day_number" : 2, "day_name" : "Tuesday", "day_weight" : .3},
                      "wed": {"day_number" : 3, "day_name" : "Wednesday", "day_weight" : .5},
                      "thu": {"day_number" : 4, "day_name" : "Thursday", "day_weight" : .6},
                      "fri": {"day_number" : 5, "day_name" : "Friday", "day_weight" :.9},
                      "sat": {"day_number" : 6, "day_name" : "Saturday", "day_weight" : .3},
                      "sun": {"day_number" : 7, "day_name" : "Sunday", "day_weight" : 0}
},
"hour_mean" : 20.1,
"hour_std" : 2.08,
"plan_probability" : {"1": 0.4, "2": 0.3, "3" : 0.2, "4": 0.1}
},
"6" :{
"name" : "full_random",
"days_probability" : {"mon": {"day_number" : 1, "day_name" : "Monday", "day_weight" : .5},
                      "tue": {"day_number" : 2, "day_name" : "Tuesday", "day_weight" : .5},
                      "wed": {"day_number" : 3, "day_name" : "Wednesday", "day_weight" : .5},
                      "thu": {"day_number" : 4, "day_name" : "Thursday", "day_weight" : 5},
                      "fri": {"day_number" : 5, "day_name" : "Friday", "day_weight" :.5},
                      "sat": {"day_number" : 6, "day_name" : "Saturday", "day_weight" : .5},
                      "sun": {"day_number" : 7, "day_name" : "Sunday", "day_weight" : 0}
},
"hour_mean" : 14.00,
"hour_std" : 3.0,
"plan_probability" : {"1": 0.59, "2": 0.3, "3" : 0.1, "4": 0.01}
},
"7" :{
"name" : "rare_random",
"days_probability" : {"mon": {"day_number" : 1, "day_name" : "Monday", "day_weight" : .2},
                      "tue": {"day_number" : 2, "day_name" : "Tuesday", "day_weight" : .2},
                      "wed": {"day_number" : 3, "day_name" : "Wednesday", "day_weight" : .4},
                      "thu": {"day_number" : 4, "day_name" : "Thursday", "day_weight" : .2},
                      "fri": {"day_number" : 5, "day_name" : "Friday", "day_weight" :.3},
                      "sat": {"day_number" : 6, "day_name" : "Saturday", "day_weight" : .4},
                      "sun": {"day_number" : 7, "day_name" : "Sunday", "day_weight" : 0}
},
"hour_mean" : 16.0,
"hour_std" : 3.5,
"plan_probability" : {"1": 0.85, "2": 0.1, "3" : 0.05, "4": 0}
},
"8" :{
"name" : "ultrarare_random",
"days_probability" : {"mon": {"day_number" : 1, "day_name" : "Monday", "day_weight" : .1},
                      "tue": {"day_number" : 2, "day_name" : "Tuesday", "day_weight" : .2},
                      "wed": {"day_number" : 3, "day_name" : "Wednesday", "day_weight" : .1},
                      "thu": {"day_number" : 4, "day_name" : "Thursday", "day_weight" : .1},
                      "fri": {"day_number" : 5, "day_name" : "Friday", "day_weight" :.2},
                      "sat": {"day_number" : 6, "day_name" : "Saturday", "day_weight" : .3},
                      "sun": {"day_number" : 7, "day_name" : "Sunday", "day_weight" : 0}
},
"hour_mean" : 14.5,
"hour_std" : 5.5,
"plan_probability" : {"1": 0.9, "2": 0.08, "3" : 0.02, "4": 0}
}
}

profile_weights = {"1" : 0.23076923, "2": 0.12820513, "3" : 0.25641026, "4" : 0.07692308, "5" : 0.07692308, "6" : 0.05128205, "7" : 0.07692308, "8" : 0.1025641}

for profile in profiles.keys():
    print(profile)
    days = profiles[profile]["days_probability"]

    sum_weight = sum([days[day]["day_weight"] for day in days.keys()])
        
    for day in days.keys():
        days[day]["day_probability"] = days[day]["day_weight"] /sum_weight
    
    profiles[profile]["total_weight"] = sum_weight

    assert 1 == sum([i for i in profiles[profile]["plan_probability"].values() ])
profiles

1
2
3
4
5
6
7
8

{'1': {'name': 'frequent_morning',
  'days_probability': {'mon': {'day_number': 1,
    'day_name': 'Monday',
    'day_weight': 0.89,
    'day_probability': 0.178},
   'tue': {'day_number': 2,
    'day_name': 'Tuesday',
    'day_weight': 0.76,
    'day_probability': 0.152},
   'wed': {'day_number': 3,
    'day_name': 'Wednesday',
    'day_weight': 0.85,
    'day_probability': 0.16999999999999998},
   'thu': {'day_number': 4,
    'day_name': 'Thursday',
    'day_weight': 0.7,
    'day_probability': 0.13999999999999999},
   'fri': {'day_number': 5,
    'day_name': 'Friday',
    'day_weight': 0.9,
    'day_probability': 0.18},
   'sat': {'day_number': 6,
    'day_name': 'Saturday',
    'day_weight': 0.9,
    'day_probability': 0.18},
   'sun': {'day_number': 7,
    'day_name': 'Sunday',
    'day_weight': 0,
    'day_probability': 0.0}},
  'hour_mean': 6.43,
  'hour_std': 0.75,
  'plan_probability': {'1': 0.05, '2': 0.2, '3': 0.45, '4': 0.3},
  'total_weight': 5.0},
 '2': {'name': 'frequent_noon',
  'days_probability': {'mon': {'day_number': 1,
    'day_name': 'Monday',
    'day_weight': 0.7,
    'day_probability': 0.14957264957264957},
   'tue': {'day_number': 2,
    'day_name': 'Tuesday',
    'day_weight': 0.82,
    'day_probability': 0.1752136752136752},
   'wed': {'day_number': 3,
    'day_name': 'Wednesday',
    'day_weight': 0.67,
    'day_probability': 0.14316239316239318},
   'thu': {'day_number': 4,
    'day_name': 'Thursday',
    'day_weight': 0.87,
    'day_probability': 0.1858974358974359},
   'fri': {'day_number': 5,
    'day_name': 'Friday',
    'day_weight': 0.78,
    'day_probability': 0.16666666666666669},
   'sat': {'day_number': 6,
    'day_name': 'Saturday',
    'day_weight': 0.84,
    'day_probability': 0.1794871794871795},
   'sun': {'day_number': 7,
    'day_name': 'Sunday',
    'day_weight': 0,
    'day_probability': 0.0}},
  'hour_mean': 13.16,
  'hour_std': 1.4,
  'plan_probability': {'1': 0.2, '2': 0.5, '3': 0.25, '4': 0.05},
  'total_weight': 4.68},
 '3': {'name': 'frequent_night',
  'days_probability': {'mon': {'day_number': 1,
    'day_name': 'Monday',
    'day_weight': 0.74,
    'day_probability': 0.1678004535147392},
   'tue': {'day_number': 2,
    'day_name': 'Tuesday',
    'day_weight': 0.87,
    'day_probability': 0.19727891156462585},
   'wed': {'day_number': 3,
    'day_name': 'Wednesday',
    'day_weight': 0.76,
    'day_probability': 0.17233560090702948},
   'thu': {'day_number': 4,
    'day_name': 'Thursday',
    'day_weight': 0.84,
    'day_probability': 0.19047619047619047},
   'fri': {'day_number': 5,
    'day_name': 'Friday',
    'day_weight': 0.4,
    'day_probability': 0.09070294784580499},
   'sat': {'day_number': 6,
    'day_name': 'Saturday',
    'day_weight': 0.8,
    'day_probability': 0.18140589569160998},
   'sun': {'day_number': 7,
    'day_name': 'Sunday',
    'day_weight': 0,
    'day_probability': 0.0}},
  'hour_mean': 19.5,
  'hour_std': 1.15,
  'plan_probability': {'1': 0.15, '2': 0.15, '3': 0.45, '4': 0.25},
  'total_weight': 4.41},
 '4': {'name': 'random_morning',
  'days_probability': {'mon': {'day_number': 1,
    'day_name': 'Monday',
    'day_weight': 0.4,
    'day_probability': 0.125},
   'tue': {'day_number': 2,
    'day_name': 'Tuesday',
    'day_weight': 0.4,
    'day_probability': 0.125},
   'wed': {'day_number': 3,
    'day_name': 'Wednesday',
    'day_weight': 0.3,
    'day_probability': 0.09374999999999999},
   'thu': {'day_number': 4,
    'day_name': 'Thursday',
    'day_weight': 0.5,
    'day_probability': 0.15625},
   'fri': {'day_number': 5,
    'day_name': 'Friday',
    'day_weight': 0.6,
    'day_probability': 0.18749999999999997},
   'sat': {'day_number': 6,
    'day_name': 'Saturday',
    'day_weight': 1,
    'day_probability': 0.3125},
   'sun': {'day_number': 7,
    'day_name': 'Sunday',
    'day_weight': 0,
    'day_probability': 0.0}},
  'hour_mean': 8.5,
  'hour_std': 2.05,
  'plan_probability': {'1': 0.65, '2': 0.25, '3': 0.1, '4': 0},
  'total_weight': 3.2},
 '5': {'name': 'random_night',
  'days_probability': {'mon': {'day_number': 1,
    'day_name': 'Monday',
    'day_weight': 0.3,
    'day_probability': 0.10344827586206896},
   'tue': {'day_number': 2,
    'day_name': 'Tuesday',
    'day_weight': 0.3,
    'day_probability': 0.10344827586206896},
   'wed': {'day_number': 3,
    'day_name': 'Wednesday',
    'day_weight': 0.5,
    'day_probability': 0.1724137931034483},
   'thu': {'day_number': 4,
    'day_name': 'Thursday',
    'day_weight': 0.6,
    'day_probability': 0.20689655172413793},
   'fri': {'day_number': 5,
    'day_name': 'Friday',
    'day_weight': 0.9,
    'day_probability': 0.3103448275862069},
   'sat': {'day_number': 6,
    'day_name': 'Saturday',
    'day_weight': 0.3,
    'day_probability': 0.10344827586206896},
   'sun': {'day_number': 7,
    'day_name': 'Sunday',
    'day_weight': 0,
    'day_probability': 0.0}},
  'hour_mean': 20.1,
  'hour_std': 2.08,
  'plan_probability': {'1': 0.4, '2': 0.3, '3': 0.2, '4': 0.1},
  'total_weight': 2.9},
 '6': {'name': 'full_random',
  'days_probability': {'mon': {'day_number': 1,
    'day_name': 'Monday',
    'day_weight': 0.5,
    'day_probability': 0.06666666666666667},
   'tue': {'day_number': 2,
    'day_name': 'Tuesday',
    'day_weight': 0.5,
    'day_probability': 0.06666666666666667},
   'wed': {'day_number': 3,
    'day_name': 'Wednesday',
    'day_weight': 0.5,
    'day_probability': 0.06666666666666667},
   'thu': {'day_number': 4,
    'day_name': 'Thursday',
    'day_weight': 5,
    'day_probability': 0.6666666666666666},
   'fri': {'day_number': 5,
    'day_name': 'Friday',
    'day_weight': 0.5,
    'day_probability': 0.06666666666666667},
   'sat': {'day_number': 6,
    'day_name': 'Saturday',
    'day_weight': 0.5,
    'day_probability': 0.06666666666666667},
   'sun': {'day_number': 7,
    'day_name': 'Sunday',
    'day_weight': 0,
    'day_probability': 0.0}},
  'hour_mean': 14.0,
  'hour_std': 3.0,
  'plan_probability': {'1': 0.59, '2': 0.3, '3': 0.1, '4': 0.01},
  'total_weight': 7.5},
 '7': {'name': 'rare_random',
  'days_probability': {'mon': {'day_number': 1,
    'day_name': 'Monday',
    'day_weight': 0.2,
    'day_probability': 0.11764705882352941},
   'tue': {'day_number': 2,
    'day_name': 'Tuesday',
    'day_weight': 0.2,
    'day_probability': 0.11764705882352941},
   'wed': {'day_number': 3,
    'day_name': 'Wednesday',
    'day_weight': 0.4,
    'day_probability': 0.23529411764705882},
   'thu': {'day_number': 4,
    'day_name': 'Thursday',
    'day_weight': 0.2,
    'day_probability': 0.11764705882352941},
   'fri': {'day_number': 5,
    'day_name': 'Friday',
    'day_weight': 0.3,
    'day_probability': 0.1764705882352941},
   'sat': {'day_number': 6,
    'day_name': 'Saturday',
    'day_weight': 0.4,
    'day_probability': 0.23529411764705882},
   'sun': {'day_number': 7,
    'day_name': 'Sunday',
    'day_weight': 0,
    'day_probability': 0.0}},
  'hour_mean': 16.0,
  'hour_std': 3.5,
  'plan_probability': {'1': 0.85, '2': 0.1, '3': 0.05, '4': 0},
  'total_weight': 1.7000000000000002},
 '8': {'name': 'ultrarare_random',
  'days_probability': {'mon': {'day_number': 1,
    'day_name': 'Monday',
    'day_weight': 0.1,
    'day_probability': 0.1},
   'tue': {'day_number': 2,
    'day_name': 'Tuesday',
    'day_weight': 0.2,
    'day_probability': 0.2},
   'wed': {'day_number': 3,
    'day_name': 'Wednesday',
    'day_weight': 0.1,
    'day_probability': 0.1},
   'thu': {'day_number': 4,
    'day_name': 'Thursday',
    'day_weight': 0.1,
    'day_probability': 0.1},
   'fri': {'day_number': 5,
    'day_name': 'Friday',
    'day_weight': 0.2,
    'day_probability': 0.2},
   'sat': {'day_number': 6,
    'day_name': 'Saturday',
    'day_weight': 0.3,
    'day_probability': 0.3},
   'sun': {'day_number': 7,
    'day_name': 'Sunday',
    'day_weight': 0,
    'day_probability': 0.0}},
  'hour_mean': 14.5,
  'hour_std': 5.5,
  'plan_probability': {'1': 0.9, '2': 0.08, '3': 0.02, '4': 0},
  'total_weight': 1.0}}

In [6]:
# Functions
def create_customer_profiles(profile_weights_ : dict, n_):
    return {str(i): str(int(rng.choice( list(profile_weights.keys()), p = list(profile_weights.values()) ) ) ) for i in range(n_) }

In [7]:
create_customer_profiles(profiles, 9)

{'0': '8',
 '1': '1',
 '2': '3',
 '3': '7',
 '4': '3',
 '5': '4',
 '6': '1',
 '7': '5',
 '8': '1'}

In [8]:
# prob = np.array((.9,0.5,1,.3,.3,.2,.3,.4))

# prob/sum(prob)

In [9]:
importlib.reload(hp)

oli =hp.create_customer(zone_distances)

Creating customer
36254

In [10]:
oli

{'id': None,
 'name': 'Natividad Eva',
 'last_name': 'Montaño Nazario',
 'gender': np.False_,
 'birth_date': datetime.datetime(1985, 9, 7, 0, 0),
 'lat': 20.98821795202615,
 'lon': -101.29917077337164,
 'zipcode': 36254,
 'email': 'q***************w@gmail.com',
 'phone_number': '(473)6043690',
 'created_at': datetime.datetime(2026, 6, 1, 21, 36, 27, 105128),
 'status': 'Active',
 'profile_type': None,
 'updated_at': datetime.datetime(2026, 6, 1, 21, 36, 27, 105134)}

In [11]:
def create_customer_access_data(date_, profile_metadata_, gym_hours_, data_path_ = "../data/", customers_file_ = "customers.csv", payment_file_ = "payments.csv", access_file_ = "access.csv", plans_file_ = "suscription_plans.csv"):
    
    opening_date = "2026-01-02"

    assert date_ >= opening_date, f"Gym doesn't exists before {opening_date}"

    # Define Schemas
    customers_schema = {"Customer_Id" :pl.Int64,
                        "Name": pl.String,
                        "Last_Name": pl.String,
                        "Gender" : pl.Boolean,
                        "Birth_Date" : pl.Datetime,
                        "Latitude": pl.Float32,
                        "Longitude" : pl.Float32,
                        "Zipcode" : pl.Int64 ,
                        "Email" : pl.String,
                        "Phone_Number" : pl.String,
                        "Created_At" : pl.Date,
                        "Status" : pl.String,
                        "Profile_Type" : pl.String,
                        "Updated_At" : pl.Datetime}
    

    payments_schema = {"Payment_Id" : pl.String,
                       "Plan_Id" : pl.Int64,
                       "Customer_Id" : pl.Int64,
                       "Payment_Amount" : pl.Float16,
                       "Payment_Time" : pl.Datetime,
                       "Plan_Expiration_Time" : pl.Datetime,
                       "Payment_Status": pl.String,
                       "Updated_At" : pl.Datetime
    }

    access_schema = {"Visit_Id" : pl.Int64,
                     "Customer_Id" : pl.Int64,
                     "Plan_Id" : pl.Int64,
                     "Branch_Id" : pl.Int8,
                     "Payment_Id" : pl.String,
                     "Date" : pl.Date,
                     "Visit_Time" : pl.Datetime,
                     "Updated_At" : pl.Datetime
    }

    suscription_plan_schema = {"Plan_Id" : pl.Int64,
                                "Plan_Name" : pl.String,
                                "Plan_Cost" : pl.Float16, 
                                "Plan_Duration" : pl.Int64,
                                "Plan_Start_Time" : pl.Datetime, 
                                "Plan_End_Time" : pl.Datetime, 
                                "Plan_Description" :pl.String,
                                "Updated_At": pl.Datetime
                                }
    
    eval_date = dt.datetime.strptime(date_, "%Y-%m-%d")
    day_names_dic = {0 : 'Monday', 1: 'Tuesday', 2: 'Wednesday', 3: 'Thursday', 4:'Friday', 5:'Saturday', 6: 'Sunday'}
    day_of_week = eval_date.weekday()
    day_name = day_names_dic[day_of_week]

    print(eval_date, day_of_week, day_name)
    
    if not os.path.isdir(data_path_):
        os.makedirs(data_path_, exist_ok = True)

    if not os.path.exists(data_path_ + customers_file_):
        print("Creating customers file")
        df_customers = pl.DataFrame([], schema = customers_schema,
                                                    orient="row").write_csv(data_path_+ customers_file_)
    
    if not os.path.exists(data_path_ + payment_file_):
        print("Creating payments file")
        df_payments = pl.DataFrame([], schema = payments_schema,
                                                    orient="row").write_csv(data_path_+ payment_file_)
        
    if not os.path.exists(data_path_ + access_file_):
        print("Creating access registry file")
        df_access = pl.DataFrame([], schema = access_schema,
                                                    orient="row").write_csv(data_path_+ access_file_)

    df_customers = pl.read_csv(data_path_+ customers_file_, schema=customers_schema)
    df_access = pl.read_csv(data_path_+ access_file_, schema=access_schema)
    df_plans = pl.read_csv(data_path_ + plans_file_, schema = suscription_plan_schema)
    df_payments = pl.read_csv(data_path_+ payment_file_, schema=payments_schema)
    
    #########################
    # 1. Create new customers
    #########################

    # 1.1. Customers configs
    tot_new = int(abs(rng.normal(0, 1)))

    max_id = df_customers.select(pl.max("Customer_Id")).item()

    print(max_id)
    counter = max_id
    if max_id == None:
        counter = 0
        tot_new = 12

    print("Total new customers", tot_new)
    counter += 1 

    dict_profiles = create_customer_profiles(profile_metadata_, tot_new)

    # 1.2 Generate customers
    new_customers = []
    new_customers_ids = []
    for new_cus in range(tot_new):

        new_customer = hp.create_customer(zone_distances)
        new_customer["id"] = counter
        new_customer["profile_type"] = dict_profiles[str(new_cus)]
        new_customer["created_at"] = dt.datetime.strptime(date_, "%Y-%m-%d").date()

        new_customers.append(tuple(new_customer.values()))
        new_customers_ids.append(counter)
        counter +=1

    # 1.3 Save file
    df_new_customers = pl.DataFrame(new_customers, customers_schema, orient = "row")
    df_customers = pl.concat([df_customers, df_new_customers])
    df_customers.write_csv(data_path_ + customers_file_)

    ###########################
    # 2. Create Access Registry
    ###########################

    # 2.1 Given at least one customer, generate random visits
    if df_customers.shape[0] >0:
        day_cus = df_customers.filter(pl.col("Status") =="Active").to_dicts()

        
        payments = []
        access = []
        
        access_count = df_access.select(pl.max("Visit_Id")).item()
        if access_count == None:
            access_count = 0

        for row in day_cus:
            cus_id = row["Customer_Id"]
            profile = str(row["Profile_Type"])
            profile_data = profile_metadata_[profile]
            day_proba  = profile_data["days_probability"][day_name[0:3].lower()]["day_probability"]

            has_visit = rng.choice([1,0], p = [day_proba, 1-day_proba])

            if max_id == None:
                has_visit = 1

            customer_new = "old customer"
            if cus_id in new_customers_ids: # If it's a new customer, has to enter gym
                has_visit = 1
                customer_new = "new_customer"

            print(f"({customer_new}) Customer {cus_id} with profile {profile} appeared {bool(has_visit)}")

            # Check is customer assisted
            if has_visit == 0:
                continue
            
            ######################
            # 2.2. Create Payments
            ######################

            #Check if plan is still active
            temp_pay = df_payments.filter(pl.col("Customer_Id") == cus_id).sort(by = ["Plan_Expiration_Time"], descending=[True])
            #display(temp_pay)
            payment_count = temp_pay.shape[0]

            
            expiration_date = temp_pay.select(pl.max("Plan_Expiration_Time")).item()

            while True:
                arrival_time = rng.normal(profile_data["hour_mean"], profile_data["hour_std"])
                if (arrival_time >= gym_hours_['open']) and (arrival_time < gym_hours_["close"]-1):
                    break
            
            arrival_hour = int(arrival_time)
            arrival_minute = int(arrival_time % arrival_hour * 60)
            
            arrival_time_obj = dt.time(arrival_hour, arrival_minute, rng.integers(0,59))

            plan_choice = 0
            #display(temp_pay.head(1))
            
            last_pay = temp_pay.head(1)
            if last_pay.is_empty() == False:
                plan_choice = last_pay.select(pl.col("Plan_Id")).item()
                print("checando plan_choice", plan_choice)

            momentum_pass_visits = 0
            if plan_choice == 2:
                payment_id = df_access.filter(pl.col("Customer_Id") == cus_id).sort(by = ["Visit_Id"], descending=[True]).head(1).select(pl.col("Payment_Id")).item()
                momentum_pass_visits += df_access.filter(pl.col("Payment_Id") == payment_id).shape[0]
            # Generate payment if conditions are meet

            print(payment_count, expiration_date, momentum_pass_visits)
            if (payment_count == 0) or (expiration_date < dt.datetime.combine(dt.datetime.strptime(date_, "%Y-%m-%d"), arrival_time_obj)) or (momentum_pass_visits >= 5) :
                
                plan_choice = int(rng.choice( list(profile_metadata_[profile]["plan_probability"].keys()), p= list(profile_metadata_[profile]["plan_probability"].values())))

                if cus_id in new_customers_ids: # If it's a new customer, has to enter gym
                    plan_choice = 1

                print(f"Customer {cus_id} is paying plan {plan_choice}")

                temp_plan  = df_plans.filter(pl.col("Plan_Id")== plan_choice)

                amount = temp_plan.select(pl.col("Plan_Cost")).item()
                duration = temp_plan.select(pl.col("Plan_Duration")).item()
                payment_count +=1
                payments_dict = {"Payment_Id" : str(cus_id) + "-" + str(payment_count),
                                "Plan_Id" : plan_choice,
                                "Customer_Id" : cus_id,
                                "Payment_Amount" : amount,
                                "Payment_Time" : dt.datetime.combine(dt.datetime.strptime(date_, "%Y-%m-%d"), arrival_time_obj),
                                "Plan_Expiration_Time" : dt.datetime.strptime(date_, "%Y-%m-%d").replace(hour = 23, minute= 59, second = 59) + dt.timedelta(days = duration -1),
                                "Payment_Status": "Completed",
                                "Updated_At" : dt.datetime.combine(dt.datetime.strptime(date_, "%Y-%m-%d"), arrival_time_obj)
                }

                payments.append(tuple(payments_dict.values()))

            
                # df_new_payments = pl.DataFrame(payments, schema = payments_schema, orient = "row")
                # df_payments = pl.concat([df_payments, df_new_payments])
                # df_payments.write_csv(data_path_+ payment_file_)
            
            # Generate access
            df_access = pl.read_csv(data_path_+ access_file_, schema=access_schema)

            visit_time = rng.normal(profile_data["hour_mean"], profile_data["hour_std"])

            # if plan_choice  == None:
            #      plan_choice = temp_pay.select(pl.col("Plan_Id")).head(1).item()
            #      print("checando plan_choice", plan_choice)

            access_dict = {"Visit_Id" : access_count + 1,
                    "Customer_Id" : cus_id,
                    "Plan_Id" : plan_choice,
                    "Branch_Id" : 1,
                    "Payment_Id" : str(cus_id) + "-" + str(payment_count),
                    "Date" : dt.datetime.strptime(date_, "%Y-%m-%d").date(),
                    "Visit_Time" : dt.datetime.combine(dt.datetime.strptime(date_, "%Y-%m-%d"), arrival_time_obj),
                    "Updated_At" : dt.datetime.combine(dt.datetime.strptime(date_, "%Y-%m-%d"), arrival_time_obj)
                    }

            access_count += 1

            access.append(tuple(access_dict.values()))

    df_new_accesss = pl.DataFrame(access, schema = access_schema, orient = "row")
    df_access = pl.concat([df_access, df_new_accesss])
    df_access.write_csv(data_path_+ access_file_)

    df_new_payments = pl.DataFrame(payments, schema = payments_schema, orient = "row")
    df_payments = pl.concat([df_payments, df_new_payments])
    df_payments.write_csv(data_path_+ payment_file_)

    return df_customers, df_payments, df_access

In [12]:
[day.strftime("%Y-%m-%d") for day in pd.date_range(start= "2026-01-02", end = "2026-01-10")]

['2026-01-02',
 '2026-01-03',
 '2026-01-04',
 '2026-01-05',
 '2026-01-06',
 '2026-01-07',
 '2026-01-08',
 '2026-01-09',
 '2026-01-10']

In [13]:
for m_day in [day.strftime("%Y-%m-%d") for day in pd.date_range(start= "2026-02-01", end = "2026-05-30")]:
    datasets = create_customer_access_data(m_day, profiles, gym_hours)

display(datasets[0])
display(datasets[1])
display(datasets[2])

2026-02-01 00:00:00 6 Sunday
68
Total new customers 2
Creating customer
36265
Creating customer
36253
(old customer) Customer 1 with profile 5 appeared False
(old customer) Customer 2 with profile 5 appeared False
(old customer) Customer 3 with profile 1 appeared False
(old customer) Customer 4 with profile 8 appeared False
(old customer) Customer 5 with profile 1 appeared False
(old customer) Customer 6 with profile 5 appeared False
(old customer) Customer 7 with profile 8 appeared False
(old customer) Customer 8 with profile 1 appeared False
(old customer) Customer 9 with profile 1 appeared False
(old customer) Customer 10 with profile 4 appeared False
(old customer) Customer 11 with profile 3 appeared False
(old customer) Customer 12 with profile 3 appeared False
(old customer) Customer 13 with profile 3 appeared False
(old customer) Customer 14 with profile 8 appeared False
(old customer) Customer 15 with profile 2 appeared False
(old customer) Customer 16 with profile 4 appeared False
(old customer) Customer 17 with profile 3 appeared False
(old customer) Customer 18 with profile 3 appeared False
(old customer) Customer 19 with profile 4 appeared False
(old customer) Customer 20 with profile 3 appeared False
(old customer) Customer 21 with profile 3 appeared False
(old customer) Customer 22 with profile 2 appeared False
(old customer) Customer 23 with profile 3 appeared False
(old customer) Customer 24 with profile 7 appeared False
(old customer) Customer 25 with profile 4 appeared False
(old customer) Customer 26 with profile 1 appeared False
(old customer) Customer 27 with profile 3 appeared False
(old customer) Customer 28 with profile 8 appeared False
(old customer) Customer 29 with profile 1 appeared False
(old customer) Customer 30 with profile 1 appeared False
(old customer) Customer 31 with profile 3 appeared False
(old customer) Customer 32 with profile 5 appeared False
(old customer) Customer 33 with profile 1 appeared False
(old customer) Customer 34 with profile 2 appeared False
(old customer) Customer 35 with profile 2 appeared False
(old customer) Customer 36 with profile 5 appeared False
(old customer) Customer 37 with profile 8 appeared False
(old customer) Customer 38 with profile 6 appeared False
(old customer) Customer 39 with profile 6 appeared False
(old customer) Customer 40 with profile 3 appeared False
(old customer) Customer 41 with profile 4 appeared False
(old customer) Customer 42 with profile 3 appeared False
(old customer) Customer 43 with profile 7 appeared False
(old customer) Customer 44 with profile 3 appeared False
(old customer) Customer 45 with profile 3 appeared False
(old customer) Customer 46 with profile 1 appeared False
(old customer) Customer 47 with profile 3 appeared False
(old customer) Customer 48 with profile 8 appeared False
(old customer) Customer 49 with profile 2 appeared False
(old customer) Customer 50 with profile 5 appeared False
(old customer) Customer 51 with profile 5 appeared False
(old customer) Customer 52 with profile 1 appeared False
(old customer) Customer 53 with profile 3 appeared False
(old customer) Customer 54 with profile 1 appeared False
(old customer) Customer 55 with profile 5 appeared False
(old customer) Customer 56 with profile 6 appeared False
(old customer) Customer 57 with profile 2 appeared False
(old customer) Customer 58 with profile 3 appeared False
(old customer) Customer 59 with profile 4 appeared False
(old customer) Customer 60 with profile 5 appeared False
(old customer) Customer 61 with profile 1 appeared False
(old customer) Customer 62 with profile 2 appeared False
(old customer) Customer 63 with profile 2 appeared False
(old customer) Customer 64 with profile 3 appeared False
(old customer) Customer 65 with profile 8 appeared False
(old customer) Customer 66 with profile 6 appeared False
(old customer) Customer 67 with profile 3 appeared False
(old customer) Customer 68 with profile 3 appeared False
(new_customer) Customer 69 with profile 3 appeared True
0 None 0
Customer 69 is paying plan 1
(new_customer) Customer 70 with profile 1 appeared True
0 None 0
Customer 70 is paying plan 1
2026-02-02 00:00:00 0 Monday
70
Total new customers 0
(old customer) Customer 1 with profile 5 appeared False
(old customer) Customer 2 with profile 5 appeared False
(old customer) Customer 3 with profile 1 appeared False
(old customer) Customer 4 with profile 8 appeared False
(old customer) Customer 5 with profile 1 appeared False
(old customer) Customer 6 with profile 5 appeared False
(old customer) Customer 7 with profile 8 appeared False
(old customer) Customer 8 with profile 1 appeared False
(old customer) Customer 9 with profile 1 appeared True
checando plan_choice 3
7 2026-06-23 23:59:59 0
(old customer) Customer 10 with profile 4 appeared False
(old customer) Customer 11 with profile 3 appeared True
checando plan_choice 4
3 2027-02-01 23:59:59 0
(old customer) Customer 12 with profile 3 appeared False
(old customer) Customer 13 with profile 3 appeared True
checando plan_choice 4
4 2027-04-23 23:59:59 0
(old customer) Customer 14 with profile 8 appeared False
(old customer) Customer 15 with profile 2 appeared False
(old customer) Customer 16 with profile 4 appeared False
(old customer) Customer 17 with profile 3 appeared False
(old customer) Customer 18 with profile 3 appeared False
(old customer) Customer 19 with profile 4 appeared False
(old customer) Customer 20 with profile 3 appeared False
(old customer) Customer 21 with profile 3 appeared False
(old customer) Customer 22 with profile 2 appeared False
(old customer) Customer 23 with profile 3 appeared False
(old customer) Customer 24 with profile 7 appeared False
(old customer) Customer 25 with profile 4 appeared False
(old customer) Customer 26 with profile 1 appeared True
checando plan_choice 4
3 2027-03-19 23:59:59 0
(old customer) Customer 27 with profile 3 appeared False
(old customer) Customer 28 with profile 8 appeared False
(old customer) Customer 29 with profile 1 appeared False
(old customer) Customer 30 with profile 1 appeared False
(old customer) Customer 31 with profile 3 appeared False
(old customer) Customer 32 with profile 5 appeared True
checando plan_choice 4
2 2027-03-06 23:59:59 0
(old customer) Customer 33 with profile 1 appeared False
(old customer) Customer 34 with profile 2 appeared False
(old customer) Customer 35 with profile 2 appeared False
(old customer) Customer 36 with profile 5 appeared False
(old customer) Customer 37 with profile 8 appeared False
(old customer) Customer 38 with profile 6 appeared False
(old customer) Customer 39 with profile 6 appeared False
(old customer) Customer 40 with profile 3 appeared False
(old customer) Customer 41 with profile 4 appeared True
checando plan_choice 2
5 2026-06-28 23:59:59 1
(old customer) Customer 42 with profile 3 appeared False
(old customer) Customer 43 with profile 7 appeared False
(old customer) Customer 44 with profile 3 appeared False
(old customer) Customer 45 with profile 3 appeared False
(old customer) Customer 46 with profile 1 appeared True
checando plan_choice 2
3 2026-06-23 23:59:59 3
(old customer) Customer 47 with profile 3 appeared True
checando plan_choice 4
5 2027-05-22 23:59:59 0
(old customer) Customer 48 with profile 8 appeared False
(old customer) Customer 49 with profile 2 appeared False
(old customer) Customer 50 with profile 5 appeared False
(old customer) Customer 51 with profile 5 appeared False
(old customer) Customer 52 with profile 1 appeared False
(old customer) Customer 53 with profile 3 appeared False
(old customer) Customer 54 with profile 1 appeared False
(old customer) Customer 55 with profile 5 appeared False
(old customer) Customer 56 with profile 6 appeared False
(old customer) Customer 57 with profile 2 appeared False
(old customer) Customer 58 with profile 3 appeared False
(old customer) Customer 59 with profile 4 appeared False
(old customer) Customer 60 with profile 5 appeared False
(old customer) Customer 61 with profile 1 appeared True
checando plan_choice 2
2 2026-06-27 23:59:59 1
(old customer) Customer 62 with profile 2 appeared False
(old customer) Customer 63 with profile 2 appeared False
(old customer) Customer 64 with profile 3 appeared False
(old customer) Customer 65 with profile 8 appeared False
(old customer) Customer 66 with profile 6 appeared True
checando plan_choice 1
1 2026-05-27 23:59:59 0
(old customer) Customer 67 with profile 3 appeared True
checando plan_choice 4
2 2027-05-28 23:59:59 0
(old customer) Customer 68 with profile 3 appeared False
(old customer) Customer 69 with profile 3 appeared True
checando plan_choice 1
1 2026-02-01 23:59:59 0
Customer 69 is paying plan 3
(old customer) Customer 70 with profile 1 appeared False
2026-02-03 00:00:00 1 Tuesday
70
Total new customers 0
(old customer) Customer 1 with profile 5 appeared False
(old customer) Customer 2 with profile 5 appeared False
(old customer) Customer 3 with profile 1 appeared False
(old customer) Customer 4 with profile 8 appeared False
(old customer) Customer 5 with profile 1 appeared False
(old customer) Customer 6 with profile 5 appeared False
(old customer) Customer 7 with profile 8 appeared False
(old customer) Customer 8 with profile 1 appeared False
(old customer) Customer 9 with profile 1 appeared False
(old customer) Customer 10 with profile 4 appeared False
(old customer) Customer 11 with profile 3 appeared False
(old customer) Customer 12 with profile 3 appeared False
(old customer) Customer 13 with profile 3 appeared True
checando plan_choice 4
4 2027-04-23 23:59:59 0
(old customer) Customer 14 with profile 8 appeared False
(old customer) Customer 15 with profile 2 appeared False
(old customer) Customer 16 with profile 4 appeared False
(old customer) Customer 17 with profile 3 appeared False
(old customer) Customer 18 with profile 3 appeared True
checando plan_choice 4
2 2027-01-21 23:59:59 0
(old customer) Customer 19 with profile 4 appeared False
(old customer) Customer 20 with profile 3 appeared False
(old customer) Customer 21 with profile 3 appeared True
checando plan_choice 4
5 2027-05-04 23:59:59 0
(old customer) Customer 22 with profile 2 appeared True
checando plan_choice 1
6 2026-05-20 23:59:59 0
(old customer) Customer 23 with profile 3 appeared False
(old customer) Customer 24 with profile 7 appeared False
(old customer) Customer 25 with profile 4 appeared True
checando plan_choice 2
6 2026-05-31 23:59:59 5
Customer 25 is paying plan 1
(old customer) Customer 26 with profile 1 appeared False
(old customer) Customer 27 with profile 3 appeared False
(old customer) Customer 28 with profile 8 appeared False
(old customer) Customer 29 with profile 1 appeared False
(old customer) Customer 30 with profile 1 appeared False
(old customer) Customer 31 with profile 3 appeared False
(old customer) Customer 32 with profile 5 appeared False
(old customer) Customer 33 with profile 1 appeared False
(old customer) Customer 34 with profile 2 appeared False
(old customer) Customer 35 with profile 2 appeared False
(old customer) Customer 36 with profile 5 appeared False
(old customer) Customer 37 with profile 8 appeared False
(old customer) Customer 38 with profile 6 appeared False
(old customer) Customer 39 with profile 6 appeared False
(old customer) Customer 40 with profile 3 appeared True
checando plan_choice 4
3 2027-04-28 23:59:59 0
(old customer) Customer 41 with profile 4 appeared False
(old customer) Customer 42 with profile 3 appeared False
(old customer) Customer 43 with profile 7 appeared False
(old customer) Customer 44 with profile 3 appeared False
(old customer) Customer 45 with profile 3 appeared False
(old customer) Customer 46 with profile 1 appeared False
(old customer) Customer 47 with profile 3 appeared False
(old customer) Customer 48 with profile 8 appeared True
checando plan_choice 1
12 2026-05-30 23:59:59 0
(old customer) Customer 49 with profile 2 appeared False
(old customer) Customer 50 with profile 5 appeared False
(old customer) Customer 51 with profile 5 appeared False
(old customer) Customer 52 with profile 1 appeared False
(old customer) Customer 53 with profile 3 appeared False
(old customer) Customer 54 with profile 1 appeared False
(old customer) Customer 55 with profile 5 appeared False
(old customer) Customer 56 with profile 6 appeared False
(old customer) Customer 57 with profile 2 appeared False
(old customer) Customer 58 with profile 3 appeared False
(old customer) Customer 59 with profile 4 appeared True
checando plan_choice 2
3 2026-06-19 23:59:59 2
(old customer) Customer 60 with profile 5 appeared False
(old customer) Customer 61 with profile 1 appeared False
(old customer) Customer 62 with profile 2 appeared True
checando plan_choice 1
4 2026-05-27 23:59:59 0
(old customer) Customer 63 with profile 2 appeared False
(old customer) Customer 64 with profile 3 appeared True
checando plan_choice 3
3 2026-06-27 23:59:59 0
(old customer) Customer 65 with profile 8 appeared True
checando plan_choice 1
2 2026-05-28 23:59:59 0
(old customer) Customer 66 with profile 6 appeared False
(old customer) Customer 67 with profile 3 appeared True
checando plan_choice 4
2 2027-05-28 23:59:59 0
(old customer) Customer 68 with profile 3 appeared False
(old customer) Customer 69 with profile 3 appeared True
checando plan_choice 3
2 2026-03-03 23:59:59 0
(old customer) Customer 70 with profile 1 appeared True
checando plan_choice 1
1 2026-02-01 23:59:59 0
Customer 70 is paying plan 3
2026-02-04 00:00:00 2 Wednesday
70
Total new customers 0
(old customer) Customer 1 with profile 5 appeared False
(old customer) Customer 2 with profile 5 appeared True
checando plan_choice 4
11 2027-05-10 23:59:59 0
(old customer) Customer 3 with profile 1 appeared True
checando plan_choice 2
6 2026-06-28 23:59:59 1
(old customer) Customer 4 with profile 8 appeared False
(old customer) Customer 5 with profile 1 appeared False
(old customer) Customer 6 with profile 5 appeared False
(old customer) Customer 7 with profile 8 appeared False
(old customer) Customer 8 with profile 1 appeared False
(old customer) Customer 9 with profile 1 appeared False
(old customer) Customer 10 with profile 4 appeared False
(old customer) Customer 11 with profile 3 appeared False
(old customer) Customer 12 with profile 3 appeared False
(old customer) Customer 13 with profile 3 appeared False
(old customer) Customer 14 with profile 8 appeared False
(old customer) Customer 15 with profile 2 appeared False
(old customer) Customer 16 with profile 4 appeared False
(old customer) Customer 17 with profile 3 appeared False
(old customer) Customer 18 with profile 3 appeared False
(old customer) Customer 19 with profile 4 appeared False
(old customer) Customer 20 with profile 3 appeared False
(old customer) Customer 21 with profile 3 appeared True
checando plan_choice 4
5 2027-05-04 23:59:59 0
(old customer) Customer 22 with profile 2 appeared False
(old customer) Customer 23 with profile 3 appeared True
checando plan_choice 4
7 2027-05-22 23:59:59 0
(old customer) Customer 24 with profile 7 appeared False
(old customer) Customer 25 with profile 4 appeared False
(old customer) Customer 26 with profile 1 appeared False
(old customer) Customer 27 with profile 3 appeared False
(old customer) Customer 28 with profile 8 appeared True
checando plan_choice 1
16 2026-05-28 23:59:59 0
(old customer) Customer 29 with profile 1 appeared False
(old customer) Customer 30 with profile 1 appeared False
(old customer) Customer 31 with profile 3 appeared False
(old customer) Customer 32 with profile 5 appeared True
checando plan_choice 4
2 2027-03-06 23:59:59 0
(old customer) Customer 33 with profile 1 appeared False
(old customer) Customer 34 with profile 2 appeared False
(old customer) Customer 35 with profile 2 appeared False
(old customer) Customer 36 with profile 5 appeared False
(old customer) Customer 37 with profile 8 appeared False
(old customer) Customer 38 with profile 6 appeared False
(old customer) Customer 39 with profile 6 appeared False
(old customer) Customer 40 with profile 3 appeared False
(old customer) Customer 41 with profile 4 appeared False
(old customer) Customer 42 with profile 3 appeared False
(old customer) Customer 43 with profile 7 appeared False
(old customer) Customer 44 with profile 3 appeared False
(old customer) Customer 45 with profile 3 appeared False
(old customer) Customer 46 with profile 1 appeared False
(old customer) Customer 47 with profile 3 appeared False
(old customer) Customer 48 with profile 8 appeared False
(old customer) Customer 49 with profile 2 appeared False
(old customer) Customer 50 with profile 5 appeared False
(old customer) Customer 51 with profile 5 appeared False
(old customer) Customer 52 with profile 1 appeared False
(old customer) Customer 53 with profile 3 appeared False
(old customer) Customer 54 with profile 1 appeared False
(old customer) Customer 55 with profile 5 appeared True
checando plan_choice 2
2 2026-06-06 23:59:59 3
(old customer) Customer 56 with profile 6 appeared False
(old customer) Customer 57 with profile 2 appeared False
(old customer) Customer 58 with profile 3 appeared False
(old customer) Customer 59 with profile 4 appeared False
(old customer) Customer 60 with profile 5 appeared False
(old customer) Customer 61 with profile 1 appeared False
(old customer) Customer 62 with profile 2 appeared False
(old customer) Customer 63 with profile 2 appeared False
(old customer) Customer 64 with profile 3 appeared True
checando plan_choice 3
3 2026-06-27 23:59:59 0
(old customer) Customer 65 with profile 8 appeared True
checando plan_choice 1
2 2026-05-28 23:59:59 0
(old customer) Customer 66 with profile 6 appeared False
(old customer) Customer 67 with profile 3 appeared False
(old customer) Customer 68 with profile 3 appeared False
(old customer) Customer 69 with profile 3 appeared False
(old customer) Customer 70 with profile 1 appeared False
2026-02-05 00:00:00 3 Thursday
70
Total new customers 1
Creating customer
36030
(old customer) Customer 1 with profile 5 appeared False
(old customer) Customer 2 with profile 5 appeared False
(old customer) Customer 3 with profile 1 appeared True
checando plan_choice 2
6 2026-06-28 23:59:59 2
(old customer) Customer 4 with profile 8 appeared False
(old customer) Customer 5 with profile 1 appeared False
(old customer) Customer 6 with profile 5 appeared False
(old customer) Customer 7 with profile 8 appeared False
(old customer) Customer 8 with profile 1 appeared False
(old customer) Customer 9 with profile 1 appeared False
(old customer) Customer 10 with profile 4 appeared False
(old customer) Customer 11 with profile 3 appeared True
checando plan_choice 4
3 2027-02-01 23:59:59 0
(old customer) Customer 12 with profile 3 appeared True
checando plan_choice 4
4 2027-03-12 23:59:59 0
(old customer) Customer 13 with profile 3 appeared False
(old customer) Customer 14 with profile 8 appeared False
(old customer) Customer 15 with profile 2 appeared False
(old customer) Customer 16 with profile 4 appeared False
(old customer) Customer 17 with profile 3 appeared True
checando plan_choice 4
2 2027-01-12 23:59:59 0
(old customer) Customer 18 with profile 3 appeared False
(old customer) Customer 19 with profile 4 appeared True
checando plan_choice 2
10 2026-06-18 23:59:59 1
(old customer) Customer 20 with profile 3 appeared False
(old customer) Customer 21 with profile 3 appeared False
(old customer) Customer 22 with profile 2 appeared False
(old customer) Customer 23 with profile 3 appeared True
checando plan_choice 4
7 2027-05-22 23:59:59 0
(old customer) Customer 24 with profile 7 appeared False
(old customer) Customer 25 with profile 4 appeared False
(old customer) Customer 26 with profile 1 appeared False
(old customer) Customer 27 with profile 3 appeared False
(old customer) Customer 28 with profile 8 appeared True
checando plan_choice 1
16 2026-05-28 23:59:59 0

shape: (111, 14)
┌────────────┬────────────┬────────────┬────────┬───┬────────────┬────────┬────────────┬───────────┐
│ Customer_I ┆ Name       ┆ Last_Name  ┆ Gender ┆ … ┆ Created_At ┆ Status ┆ Profile_Ty ┆ Updated_A │
│ d          ┆ ---        ┆ ---        ┆ ---    ┆   ┆ ---        ┆ ---    ┆ pe         ┆ t         │
│ ---        ┆ str        ┆ str        ┆ bool   ┆   ┆ date       ┆ str    ┆ ---        ┆ ---       │
│ i64        ┆            ┆            ┆        ┆   ┆            ┆        ┆ str        ┆ datetime[ │
│            ┆            ┆            ┆        ┆   ┆            ┆        ┆            ┆ μs]       │
╞════════════╪════════════╪════════════╪════════╪═══╪════════════╪════════╪════════════╪═══════════╡
│ 1          ┆ Teresa     ┆ Laboy      ┆ false  ┆ … ┆ 2026-01-02 ┆ Active ┆ 5          ┆ 2026-05-3 │
│            ┆ Irma       ┆ Mercado    ┆        ┆   ┆            ┆        ┆            ┆ 0 22:32:0 │
│            ┆            ┆            ┆        ┆   ┆            ┆        ┆            ┆ 9.090932  │
│ 2          ┆ Claudio    ┆ Sáenz      ┆ true   ┆ … ┆ 2026-01-02 ┆ Active ┆ 5          ┆ 2026-05-3 │
│            ┆ José       ┆ Barreto    ┆        ┆   ┆            ┆        ┆            ┆ 0 22:32:1 │
│            ┆            ┆            ┆        ┆   ┆            ┆        ┆            ┆ 2.727524  │
│ 3          ┆ Sergio     ┆ Villagómez ┆ true   ┆ … ┆ 2026-01-02 ┆ Active ┆ 1          ┆ 2026-05-3 │
│            ┆ Renato     ┆ Navarrete  ┆        ┆   ┆            ┆        ┆            ┆ 0 22:32:1 │
│            ┆            ┆            ┆        ┆   ┆            ┆        ┆            ┆ 6.405117  │
│ 4          ┆ Perla      ┆ Aguayo     ┆ false  ┆ … ┆ 2026-01-02 ┆ Active ┆ 8          ┆ 2026-05-3 │
│            ┆ Amanda     ┆ Mascareñas ┆        ┆   ┆            ┆        ┆            ┆ 0 22:32:1 │
│            ┆            ┆            ┆        ┆   ┆            ┆        ┆            ┆ 9.791288  │
│ 5          ┆ Genaro     ┆ Sáenz      ┆ true   ┆ … ┆ 2026-01-02 ┆ Active ┆ 1          ┆ 2026-05-3 │
│            ┆ Guillermo  ┆ Carvajal   ┆        ┆   ┆            ┆        ┆            ┆ 0 22:32:2 │
│            ┆            ┆            ┆        ┆   ┆            ┆        ┆            ┆ 3.484012  │
│ …          ┆ …          ┆ …          ┆ …      ┆ … ┆ …          ┆ …      ┆ …          ┆ …         │
│ 107        ┆ Jaime      ┆ Durán      ┆ true   ┆ … ┆ 2026-05-14 ┆ Active ┆ 2          ┆ 2026-06-0 │
│            ┆ Gregorio   ┆ Ulibarri   ┆        ┆   ┆            ┆        ┆            ┆ 1 21:38:3 │
│            ┆            ┆            ┆        ┆   ┆            ┆        ┆            ┆ 7.156801  │
│ 108        ┆ Gerónimo   ┆ Gaona      ┆ true   ┆ … ┆ 2026-05-17 ┆ Active ┆ 2          ┆ 2026-06-0 │
│            ┆ David      ┆ Verdugo    ┆        ┆   ┆            ┆        ┆            ┆ 1 21:38:4 │
│            ┆            ┆            ┆        ┆   ┆            ┆        ┆            ┆ 0.359627  │
│ 109        ┆ Patricio   ┆ Henríquez  ┆ true   ┆ … ┆ 2026-05-20 ┆ Active ┆ 4          ┆ 2026-06-0 │
│            ┆ Enrique    ┆ Hernández  ┆        ┆   ┆            ┆        ┆            ┆ 1 21:38:4 │
│            ┆            ┆            ┆        ┆   ┆            ┆        ┆            ┆ 3.532746  │
│ 110        ┆ Marcos     ┆ Prieto     ┆ true   ┆ … ┆ 2026-05-24 ┆ Active ┆ 3          ┆ 2026-06-0 │
│            ┆ Esteban    ┆ Balderas   ┆        ┆   ┆            ┆        ┆            ┆ 1 21:38:4 │
│            ┆            ┆            ┆        ┆   ┆            ┆        ┆            ┆ 6.763796  │
│ 111        ┆ Germán     ┆ Meza       ┆ true   ┆ … ┆ 2026-05-26 ┆ Active ┆ 3          ┆ 2026-06-0 │
│            ┆ Alejandro  ┆ Pedraza    ┆        ┆   ┆            ┆        ┆            ┆ 1 21:38:5 │
│            ┆            ┆            ┆        ┆   ┆            ┆        ┆            ┆ 0.040340  │
└────────────┴────────────┴────────────┴────────┴───┴────────────┴────────┴────────────┴───────────┘

shape: (659, 8)
┌────────────┬─────────┬────────────┬────────────┬────────────┬────────────┬───────────┬───────────┐
│ Payment_Id ┆ Plan_Id ┆ Customer_I ┆ Payment_Am ┆ Payment_Ti ┆ Plan_Expir ┆ Payment_S ┆ Updated_A │
│ ---        ┆ ---     ┆ d          ┆ ount       ┆ me         ┆ ation_Time ┆ tatus     ┆ t         │
│ str        ┆ i64     ┆ ---        ┆ ---        ┆ ---        ┆ ---        ┆ ---       ┆ ---       │
│            ┆         ┆ i64        ┆ f16        ┆ datetime[μ ┆ datetime[μ ┆ str       ┆ datetime[ │
│            ┆         ┆            ┆            ┆ s]         ┆ s]         ┆           ┆ μs]       │
╞════════════╪═════════╪════════════╪════════════╪════════════╪════════════╪═══════════╪═══════════╡
│ 1-1        ┆ 1       ┆ 1          ┆ 150.0      ┆ 2026-01-02 ┆ 2026-01-02 ┆ Completed ┆ 2026-01-0 │
│            ┆         ┆            ┆            ┆ 20:10:22   ┆ 23:59:59   ┆           ┆ 2         │
│            ┆         ┆            ┆            ┆            ┆            ┆           ┆ 20:10:22  │
│ 2-1        ┆ 1       ┆ 2          ┆ 150.0      ┆ 2026-01-02 ┆ 2026-01-02 ┆ Completed ┆ 2026-01-0 │
│            ┆         ┆            ┆            ┆ 20:48:54   ┆ 23:59:59   ┆           ┆ 2         │
│            ┆         ┆            ┆            ┆            ┆            ┆           ┆ 20:48:54  │
│ 3-1        ┆ 1       ┆ 3          ┆ 150.0      ┆ 2026-01-02 ┆ 2026-01-02 ┆ Completed ┆ 2026-01-0 │
│            ┆         ┆            ┆            ┆ 06:47:20   ┆ 23:59:59   ┆           ┆ 2         │
│            ┆         ┆            ┆            ┆            ┆            ┆           ┆ 06:47:20  │
│ 4-1        ┆ 1       ┆ 4          ┆ 150.0      ┆ 2026-01-02 ┆ 2026-01-02 ┆ Completed ┆ 2026-01-0 │
│            ┆         ┆            ┆            ┆ 19:23:07   ┆ 23:59:59   ┆           ┆ 2         │
│            ┆         ┆            ┆            ┆            ┆            ┆           ┆ 19:23:07  │
│ 5-1        ┆ 1       ┆ 5          ┆ 150.0      ┆ 2026-01-02 ┆ 2026-01-02 ┆ Completed ┆ 2026-01-0 │
│            ┆         ┆            ┆            ┆ 07:50:41   ┆ 23:59:59   ┆           ┆ 2         │
│            ┆         ┆            ┆            ┆            ┆            ┆           ┆ 07:50:41  │
│ …          ┆ …       ┆ …          ┆ …          ┆ …          ┆ …          ┆ …         ┆ …         │
│ 88-7       ┆ 2       ┆ 88         ┆ 650.0      ┆ 2026-05-30 ┆ 2026-06-28 ┆ Completed ┆ 2026-05-3 │
│            ┆         ┆            ┆            ┆ 08:34:53   ┆ 23:59:59   ┆           ┆ 0         │
│            ┆         ┆            ┆            ┆            ┆            ┆           ┆ 08:34:53  │
│ 89-10      ┆ 1       ┆ 89         ┆ 150.0      ┆ 2026-05-30 ┆ 2026-05-30 ┆ Completed ┆ 2026-05-3 │
│            ┆         ┆            ┆            ┆ 15:53:02   ┆ 23:59:59   ┆           ┆ 0         │
│            ┆         ┆            ┆            ┆            ┆            ┆           ┆ 15:53:02  │
│ 99-8       ┆ 1       ┆ 99         ┆ 150.0      ┆ 2026-05-30 ┆ 2026-05-30 ┆ Completed ┆ 2026-05-3 │
│            ┆         ┆            ┆            ┆ 07:39:11   ┆ 23:59:59   ┆           ┆ 0         │
│            ┆         ┆            ┆            ┆            ┆            ┆           ┆ 07:39:11  │
│ 101-4      ┆ 1       ┆ 101        ┆ 150.0      ┆ 2026-05-30 ┆ 2026-05-30 ┆ Completed ┆ 2026-05-3 │
│            ┆         ┆            ┆            ┆ 17:44:45   ┆ 23:59:59   ┆           ┆ 0         │
│            ┆         ┆            ┆            ┆            ┆            ┆           ┆ 17:44:45  │
│ 108-3      ┆ 3       ┆ 108        ┆ 1200.0     ┆ 2026-05-30 ┆ 2026-06-28 ┆ Completed ┆ 2026-05-3 │
│            ┆         ┆            ┆            ┆ 13:47:14   ┆ 23:59:59   ┆           ┆ 0         │
│            ┆         ┆            ┆            ┆            ┆            ┆           ┆ 13:47:14  │
└────────────┴─────────┴────────────┴────────────┴────────────┴────────────┴───────────┴───────────┘

shape: (2_561, 8)
┌──────────┬─────────────┬─────────┬───────────┬────────────┬────────────┬────────────┬────────────┐
│ Visit_Id ┆ Customer_Id ┆ Plan_Id ┆ Branch_Id ┆ Payment_Id ┆ Date       ┆ Visit_Time ┆ Updated_At │
│ ---      ┆ ---         ┆ ---     ┆ ---       ┆ ---        ┆ ---        ┆ ---        ┆ ---        │
│ i64      ┆ i64         ┆ i64     ┆ i8        ┆ str        ┆ date       ┆ datetime[μ ┆ datetime[μ │
│          ┆             ┆         ┆           ┆            ┆            ┆ s]         ┆ s]         │
╞══════════╪═════════════╪═════════╪═══════════╪════════════╪════════════╪════════════╪════════════╡
│ 1        ┆ 1           ┆ 1       ┆ 1         ┆ 1-1        ┆ 2026-01-02 ┆ 2026-01-02 ┆ 2026-01-02 │
│          ┆             ┆         ┆           ┆            ┆            ┆ 20:10:22   ┆ 20:10:22   │
│ 2        ┆ 2           ┆ 1       ┆ 1         ┆ 2-1        ┆ 2026-01-02 ┆ 2026-01-02 ┆ 2026-01-02 │
│          ┆             ┆         ┆           ┆            ┆            ┆ 20:48:54   ┆ 20:48:54   │
│ 3        ┆ 3           ┆ 1       ┆ 1         ┆ 3-1        ┆ 2026-01-02 ┆ 2026-01-02 ┆ 2026-01-02 │
│          ┆             ┆         ┆           ┆            ┆            ┆ 06:47:20   ┆ 06:47:20   │
│ 4        ┆ 4           ┆ 1       ┆ 1         ┆ 4-1        ┆ 2026-01-02 ┆ 2026-01-02 ┆ 2026-01-02 │
│          ┆             ┆         ┆           ┆            ┆            ┆ 19:23:07   ┆ 19:23:07   │
│ 5        ┆ 5           ┆ 1       ┆ 1         ┆ 5-1        ┆ 2026-01-02 ┆ 2026-01-02 ┆ 2026-01-02 │
│          ┆             ┆         ┆           ┆            ┆            ┆ 07:50:41   ┆ 07:50:41   │
│ …        ┆ …           ┆ …       ┆ …         ┆ …          ┆ …          ┆ …          ┆ …          │
│ 2557     ┆ 101         ┆ 1       ┆ 1         ┆ 101-4      ┆ 2026-05-30 ┆ 2026-05-30 ┆ 2026-05-30 │
│          ┆             ┆         ┆           ┆            ┆            ┆ 17:44:45   ┆ 17:44:45   │
│ 2558     ┆ 102         ┆ 4       ┆ 1         ┆ 102-2      ┆ 2026-05-30 ┆ 2026-05-30 ┆ 2026-05-30 │
│          ┆             ┆         ┆           ┆            ┆            ┆ 07:04:55   ┆ 07:04:55   │
│ 2559     ┆ 103         ┆ 4       ┆ 1         ┆ 103-2      ┆ 2026-05-30 ┆ 2026-05-30 ┆ 2026-05-30 │
│          ┆             ┆         ┆           ┆            ┆            ┆ 06:18:17   ┆ 06:18:17   │
│ 2560     ┆ 106         ┆ 2       ┆ 1         ┆ 106-2      ┆ 2026-05-30 ┆ 2026-05-30 ┆ 2026-05-30 │
│          ┆             ┆         ┆           ┆            ┆            ┆ 11:49:18   ┆ 11:49:18   │
│ 2561     ┆ 108         ┆ 3       ┆ 1         ┆ 108-3      ┆ 2026-05-30 ┆ 2026-05-30 ┆ 2026-05-30 │
│          ┆             ┆         ┆           ┆            ┆            ┆ 13:47:14   ┆ 13:47:14   │
└──────────┴─────────────┴─────────┴───────────┴────────────┴────────────┴────────────┴────────────┘

In [14]:
display(datasets[0])
display(datasets[1])
display(datasets[2])

shape: (111, 14)
┌────────────┬────────────┬────────────┬────────┬───┬────────────┬────────┬────────────┬───────────┐
│ Customer_I ┆ Name       ┆ Last_Name  ┆ Gender ┆ … ┆ Created_At ┆ Status ┆ Profile_Ty ┆ Updated_A │
│ d          ┆ ---        ┆ ---        ┆ ---    ┆   ┆ ---        ┆ ---    ┆ pe         ┆ t         │
│ ---        ┆ str        ┆ str        ┆ bool   ┆   ┆ date       ┆ str    ┆ ---        ┆ ---       │
│ i64        ┆            ┆            ┆        ┆   ┆            ┆        ┆ str        ┆ datetime[ │
│            ┆            ┆            ┆        ┆   ┆            ┆        ┆            ┆ μs]       │
╞════════════╪════════════╪════════════╪════════╪═══╪════════════╪════════╪════════════╪═══════════╡
│ 1          ┆ Teresa     ┆ Laboy      ┆ false  ┆ … ┆ 2026-01-02 ┆ Active ┆ 5          ┆ 2026-05-3 │
│            ┆ Irma       ┆ Mercado    ┆        ┆   ┆            ┆        ┆            ┆ 0 22:32:0 │
│            ┆            ┆            ┆        ┆   ┆            ┆        ┆            ┆ 9.090932  │
│ 2          ┆ Claudio    ┆ Sáenz      ┆ true   ┆ … ┆ 2026-01-02 ┆ Active ┆ 5          ┆ 2026-05-3 │
│            ┆ José       ┆ Barreto    ┆        ┆   ┆            ┆        ┆            ┆ 0 22:32:1 │
│            ┆            ┆            ┆        ┆   ┆            ┆        ┆            ┆ 2.727524  │
│ 3          ┆ Sergio     ┆ Villagómez ┆ true   ┆ … ┆ 2026-01-02 ┆ Active ┆ 1          ┆ 2026-05-3 │
│            ┆ Renato     ┆ Navarrete  ┆        ┆   ┆            ┆        ┆            ┆ 0 22:32:1 │
│            ┆            ┆            ┆        ┆   ┆            ┆        ┆            ┆ 6.405117  │
│ 4          ┆ Perla      ┆ Aguayo     ┆ false  ┆ … ┆ 2026-01-02 ┆ Active ┆ 8          ┆ 2026-05-3 │
│            ┆ Amanda     ┆ Mascareñas ┆        ┆   ┆            ┆        ┆            ┆ 0 22:32:1 │
│            ┆            ┆            ┆        ┆   ┆            ┆        ┆            ┆ 9.791288  │
│ 5          ┆ Genaro     ┆ Sáenz      ┆ true   ┆ … ┆ 2026-01-02 ┆ Active ┆ 1          ┆ 2026-05-3 │
│            ┆ Guillermo  ┆ Carvajal   ┆        ┆   ┆            ┆        ┆            ┆ 0 22:32:2 │
│            ┆            ┆            ┆        ┆   ┆            ┆        ┆            ┆ 3.484012  │
│ …          ┆ …          ┆ …          ┆ …      ┆ … ┆ …          ┆ …      ┆ …          ┆ …         │
│ 107        ┆ Jaime      ┆ Durán      ┆ true   ┆ … ┆ 2026-05-14 ┆ Active ┆ 2          ┆ 2026-06-0 │
│            ┆ Gregorio   ┆ Ulibarri   ┆        ┆   ┆            ┆        ┆            ┆ 1 21:38:3 │
│            ┆            ┆            ┆        ┆   ┆            ┆        ┆            ┆ 7.156801  │
│ 108        ┆ Gerónimo   ┆ Gaona      ┆ true   ┆ … ┆ 2026-05-17 ┆ Active ┆ 2          ┆ 2026-06-0 │
│            ┆ David      ┆ Verdugo    ┆        ┆   ┆            ┆        ┆            ┆ 1 21:38:4 │
│            ┆            ┆            ┆        ┆   ┆            ┆        ┆            ┆ 0.359627  │
│ 109        ┆ Patricio   ┆ Henríquez  ┆ true   ┆ … ┆ 2026-05-20 ┆ Active ┆ 4          ┆ 2026-06-0 │
│            ┆ Enrique    ┆ Hernández  ┆        ┆   ┆            ┆        ┆            ┆ 1 21:38:4 │
│            ┆            ┆            ┆        ┆   ┆            ┆        ┆            ┆ 3.532746  │
│ 110        ┆ Marcos     ┆ Prieto     ┆ true   ┆ … ┆ 2026-05-24 ┆ Active ┆ 3          ┆ 2026-06-0 │
│            ┆ Esteban    ┆ Balderas   ┆        ┆   ┆            ┆        ┆            ┆ 1 21:38:4 │
│            ┆            ┆            ┆        ┆   ┆            ┆        ┆            ┆ 6.763796  │
│ 111        ┆ Germán     ┆ Meza       ┆ true   ┆ … ┆ 2026-05-26 ┆ Active ┆ 3          ┆ 2026-06-0 │
│            ┆ Alejandro  ┆ Pedraza    ┆        ┆   ┆            ┆        ┆            ┆ 1 21:38:5 │
│            ┆            ┆            ┆        ┆   ┆            ┆        ┆            ┆ 0.040340  │
└────────────┴────────────┴────────────┴────────┴───┴────────────┴────────┴────────────┴───────────┘

shape: (659, 8)
┌────────────┬─────────┬────────────┬────────────┬────────────┬────────────┬───────────┬───────────┐
│ Payment_Id ┆ Plan_Id ┆ Customer_I ┆ Payment_Am ┆ Payment_Ti ┆ Plan_Expir ┆ Payment_S ┆ Updated_A │
│ ---        ┆ ---     ┆ d          ┆ ount       ┆ me         ┆ ation_Time ┆ tatus     ┆ t         │
│ str        ┆ i64     ┆ ---        ┆ ---        ┆ ---        ┆ ---        ┆ ---       ┆ ---       │
│            ┆         ┆ i64        ┆ f16        ┆ datetime[μ ┆ datetime[μ ┆ str       ┆ datetime[ │
│            ┆         ┆            ┆            ┆ s]         ┆ s]         ┆           ┆ μs]       │
╞════════════╪═════════╪════════════╪════════════╪════════════╪════════════╪═══════════╪═══════════╡
│ 1-1        ┆ 1       ┆ 1          ┆ 150.0      ┆ 2026-01-02 ┆ 2026-01-02 ┆ Completed ┆ 2026-01-0 │
│            ┆         ┆            ┆            ┆ 20:10:22   ┆ 23:59:59   ┆           ┆ 2         │
│            ┆         ┆            ┆            ┆            ┆            ┆           ┆ 20:10:22  │
│ 2-1        ┆ 1       ┆ 2          ┆ 150.0      ┆ 2026-01-02 ┆ 2026-01-02 ┆ Completed ┆ 2026-01-0 │
│            ┆         ┆            ┆            ┆ 20:48:54   ┆ 23:59:59   ┆           ┆ 2         │
│            ┆         ┆            ┆            ┆            ┆            ┆           ┆ 20:48:54  │
│ 3-1        ┆ 1       ┆ 3          ┆ 150.0      ┆ 2026-01-02 ┆ 2026-01-02 ┆ Completed ┆ 2026-01-0 │
│            ┆         ┆            ┆            ┆ 06:47:20   ┆ 23:59:59   ┆           ┆ 2         │
│            ┆         ┆            ┆            ┆            ┆            ┆           ┆ 06:47:20  │
│ 4-1        ┆ 1       ┆ 4          ┆ 150.0      ┆ 2026-01-02 ┆ 2026-01-02 ┆ Completed ┆ 2026-01-0 │
│            ┆         ┆            ┆            ┆ 19:23:07   ┆ 23:59:59   ┆           ┆ 2         │
│            ┆         ┆            ┆            ┆            ┆            ┆           ┆ 19:23:07  │
│ 5-1        ┆ 1       ┆ 5          ┆ 150.0      ┆ 2026-01-02 ┆ 2026-01-02 ┆ Completed ┆ 2026-01-0 │
│            ┆         ┆            ┆            ┆ 07:50:41   ┆ 23:59:59   ┆           ┆ 2         │
│            ┆         ┆            ┆            ┆            ┆            ┆           ┆ 07:50:41  │
│ …          ┆ …       ┆ …          ┆ …          ┆ …          ┆ …          ┆ …         ┆ …         │
│ 88-7       ┆ 2       ┆ 88         ┆ 650.0      ┆ 2026-05-30 ┆ 2026-06-28 ┆ Completed ┆ 2026-05-3 │
│            ┆         ┆            ┆            ┆ 08:34:53   ┆ 23:59:59   ┆           ┆ 0         │
│            ┆         ┆            ┆            ┆            ┆            ┆           ┆ 08:34:53  │
│ 89-10      ┆ 1       ┆ 89         ┆ 150.0      ┆ 2026-05-30 ┆ 2026-05-30 ┆ Completed ┆ 2026-05-3 │
│            ┆         ┆            ┆            ┆ 15:53:02   ┆ 23:59:59   ┆           ┆ 0         │
│            ┆         ┆            ┆            ┆            ┆            ┆           ┆ 15:53:02  │
│ 99-8       ┆ 1       ┆ 99         ┆ 150.0      ┆ 2026-05-30 ┆ 2026-05-30 ┆ Completed ┆ 2026-05-3 │
│            ┆         ┆            ┆            ┆ 07:39:11   ┆ 23:59:59   ┆           ┆ 0         │
│            ┆         ┆            ┆            ┆            ┆            ┆           ┆ 07:39:11  │
│ 101-4      ┆ 1       ┆ 101        ┆ 150.0      ┆ 2026-05-30 ┆ 2026-05-30 ┆ Completed ┆ 2026-05-3 │
│            ┆         ┆            ┆            ┆ 17:44:45   ┆ 23:59:59   ┆           ┆ 0         │
│            ┆         ┆            ┆            ┆            ┆            ┆           ┆ 17:44:45  │
│ 108-3      ┆ 3       ┆ 108        ┆ 1200.0     ┆ 2026-05-30 ┆ 2026-06-28 ┆ Completed ┆ 2026-05-3 │
│            ┆         ┆            ┆            ┆ 13:47:14   ┆ 23:59:59   ┆           ┆ 0         │
│            ┆         ┆            ┆            ┆            ┆            ┆           ┆ 13:47:14  │
└────────────┴─────────┴────────────┴────────────┴────────────┴────────────┴───────────┴───────────┘

shape: (2_561, 8)
┌──────────┬─────────────┬─────────┬───────────┬────────────┬────────────┬────────────┬────────────┐
│ Visit_Id ┆ Customer_Id ┆ Plan_Id ┆ Branch_Id ┆ Payment_Id ┆ Date       ┆ Visit_Time ┆ Updated_At │
│ ---      ┆ ---         ┆ ---     ┆ ---       ┆ ---        ┆ ---        ┆ ---        ┆ ---        │
│ i64      ┆ i64         ┆ i64     ┆ i8        ┆ str        ┆ date       ┆ datetime[μ ┆ datetime[μ │
│          ┆             ┆         ┆           ┆            ┆            ┆ s]         ┆ s]         │
╞══════════╪═════════════╪═════════╪═══════════╪════════════╪════════════╪════════════╪════════════╡
│ 1        ┆ 1           ┆ 1       ┆ 1         ┆ 1-1        ┆ 2026-01-02 ┆ 2026-01-02 ┆ 2026-01-02 │
│          ┆             ┆         ┆           ┆            ┆            ┆ 20:10:22   ┆ 20:10:22   │
│ 2        ┆ 2           ┆ 1       ┆ 1         ┆ 2-1        ┆ 2026-01-02 ┆ 2026-01-02 ┆ 2026-01-02 │
│          ┆             ┆         ┆           ┆            ┆            ┆ 20:48:54   ┆ 20:48:54   │
│ 3        ┆ 3           ┆ 1       ┆ 1         ┆ 3-1        ┆ 2026-01-02 ┆ 2026-01-02 ┆ 2026-01-02 │
│          ┆             ┆         ┆           ┆            ┆            ┆ 06:47:20   ┆ 06:47:20   │
│ 4        ┆ 4           ┆ 1       ┆ 1         ┆ 4-1        ┆ 2026-01-02 ┆ 2026-01-02 ┆ 2026-01-02 │
│          ┆             ┆         ┆           ┆            ┆            ┆ 19:23:07   ┆ 19:23:07   │
│ 5        ┆ 5           ┆ 1       ┆ 1         ┆ 5-1        ┆ 2026-01-02 ┆ 2026-01-02 ┆ 2026-01-02 │
│          ┆             ┆         ┆           ┆            ┆            ┆ 07:50:41   ┆ 07:50:41   │
│ …        ┆ …           ┆ …       ┆ …         ┆ …          ┆ …          ┆ …          ┆ …          │
│ 2557     ┆ 101         ┆ 1       ┆ 1         ┆ 101-4      ┆ 2026-05-30 ┆ 2026-05-30 ┆ 2026-05-30 │
│          ┆             ┆         ┆           ┆            ┆            ┆ 17:44:45   ┆ 17:44:45   │
│ 2558     ┆ 102         ┆ 4       ┆ 1         ┆ 102-2      ┆ 2026-05-30 ┆ 2026-05-30 ┆ 2026-05-30 │
│          ┆             ┆         ┆           ┆            ┆            ┆ 07:04:55   ┆ 07:04:55   │
│ 2559     ┆ 103         ┆ 4       ┆ 1         ┆ 103-2      ┆ 2026-05-30 ┆ 2026-05-30 ┆ 2026-05-30 │
│          ┆             ┆         ┆           ┆            ┆            ┆ 06:18:17   ┆ 06:18:17   │
│ 2560     ┆ 106         ┆ 2       ┆ 1         ┆ 106-2      ┆ 2026-05-30 ┆ 2026-05-30 ┆ 2026-05-30 │
│          ┆             ┆         ┆           ┆            ┆            ┆ 11:49:18   ┆ 11:49:18   │
│ 2561     ┆ 108         ┆ 3       ┆ 1         ┆ 108-3      ┆ 2026-05-30 ┆ 2026-05-30 ┆ 2026-05-30 │
│          ┆             ┆         ┆           ┆            ┆            ┆ 13:47:14   ┆ 13:47:14   │
└──────────┴─────────────┴─────────┴───────────┴────────────┴────────────┴────────────┴────────────┘

In [15]:
datasets[1].filter(pl.col("Customer_Id") == 4)

shape: (24, 8)
┌────────────┬─────────┬────────────┬────────────┬────────────┬────────────┬───────────┬───────────┐
│ Payment_Id ┆ Plan_Id ┆ Customer_I ┆ Payment_Am ┆ Payment_Ti ┆ Plan_Expir ┆ Payment_S ┆ Updated_A │
│ ---        ┆ ---     ┆ d          ┆ ount       ┆ me         ┆ ation_Time ┆ tatus     ┆ t         │
│ str        ┆ i64     ┆ ---        ┆ ---        ┆ ---        ┆ ---        ┆ ---       ┆ ---       │
│            ┆         ┆ i64        ┆ f16        ┆ datetime[μ ┆ datetime[μ ┆ str       ┆ datetime[ │
│            ┆         ┆            ┆            ┆ s]         ┆ s]         ┆           ┆ μs]       │
╞════════════╪═════════╪════════════╪════════════╪════════════╪════════════╪═══════════╪═══════════╡
│ 4-1        ┆ 1       ┆ 4          ┆ 150.0      ┆ 2026-01-02 ┆ 2026-01-02 ┆ Completed ┆ 2026-01-0 │
│            ┆         ┆            ┆            ┆ 19:23:07   ┆ 23:59:59   ┆           ┆ 2         │
│            ┆         ┆            ┆            ┆            ┆            ┆           ┆ 19:23:07  │
│ 4-2        ┆ 1       ┆ 4          ┆ 150.0      ┆ 2026-01-03 ┆ 2026-01-03 ┆ Completed ┆ 2026-01-0 │
│            ┆         ┆            ┆            ┆ 14:23:42   ┆ 23:59:59   ┆           ┆ 3         │
│            ┆         ┆            ┆            ┆            ┆            ┆           ┆ 14:23:42  │
│ 4-3        ┆ 1       ┆ 4          ┆ 150.0      ┆ 2026-01-05 ┆ 2026-01-05 ┆ Completed ┆ 2026-01-0 │
│            ┆         ┆            ┆            ┆ 07:32:18   ┆ 23:59:59   ┆           ┆ 5         │
│            ┆         ┆            ┆            ┆            ┆            ┆           ┆ 07:32:18  │
│ 4-4        ┆ 1       ┆ 4          ┆ 150.0      ┆ 2026-01-06 ┆ 2026-01-06 ┆ Completed ┆ 2026-01-0 │
│            ┆         ┆            ┆            ┆ 18:09:03   ┆ 23:59:59   ┆           ┆ 6         │
│            ┆         ┆            ┆            ┆            ┆            ┆           ┆ 18:09:03  │
│ 4-5        ┆ 1       ┆ 4          ┆ 150.0      ┆ 2026-01-12 ┆ 2026-01-12 ┆ Completed ┆ 2026-01-1 │
│            ┆         ┆            ┆            ┆ 16:42:15   ┆ 23:59:59   ┆           ┆ 2         │
│            ┆         ┆            ┆            ┆            ┆            ┆           ┆ 16:42:15  │
│ …          ┆ …       ┆ …          ┆ …          ┆ …          ┆ …          ┆ …         ┆ …         │
│ 4-20       ┆ 1       ┆ 4          ┆ 150.0      ┆ 2026-04-20 ┆ 2026-04-20 ┆ Completed ┆ 2026-04-2 │
│            ┆         ┆            ┆            ┆ 11:09:32   ┆ 23:59:59   ┆           ┆ 0         │
│            ┆         ┆            ┆            ┆            ┆            ┆           ┆ 11:09:32  │
│ 4-21       ┆ 1       ┆ 4          ┆ 150.0      ┆ 2026-05-01 ┆ 2026-05-01 ┆ Completed ┆ 2026-05-0 │
│            ┆         ┆            ┆            ┆ 11:01:11   ┆ 23:59:59   ┆           ┆ 1         │
│            ┆         ┆            ┆            ┆            ┆            ┆           ┆ 11:01:11  │
│ 4-22       ┆ 1       ┆ 4          ┆ 150.0      ┆ 2026-05-09 ┆ 2026-05-09 ┆ Completed ┆ 2026-05-0 │
│            ┆         ┆            ┆            ┆ 09:17:35   ┆ 23:59:59   ┆           ┆ 9         │
│            ┆         ┆            ┆            ┆            ┆            ┆           ┆ 09:17:35  │
│ 4-23       ┆ 1       ┆ 4          ┆ 150.0      ┆ 2026-05-15 ┆ 2026-05-15 ┆ Completed ┆ 2026-05-1 │
│            ┆         ┆            ┆            ┆ 15:46:10   ┆ 23:59:59   ┆           ┆ 5         │
│            ┆         ┆            ┆            ┆            ┆            ┆           ┆ 15:46:10  │
│ 4-24       ┆ 3       ┆ 4          ┆ 1200.0     ┆ 2026-05-28 ┆ 2026-06-26 ┆ Completed ┆ 2026-05-2 │
│            ┆         ┆            ┆            ┆ 13:37:19   ┆ 23:59:59   ┆           ┆ 8         │
│            ┆         ┆            ┆            ┆            ┆            ┆           ┆ 13:37:19  │
└────────────┴─────────┴────────────┴────────────┴────────────┴────────────┴───────────┴───────────┘

In [16]:
datasets[2].filter(pl.col("Customer_Id") == 4)

shape: (46, 8)
┌──────────┬─────────────┬─────────┬───────────┬────────────┬────────────┬────────────┬────────────┐
│ Visit_Id ┆ Customer_Id ┆ Plan_Id ┆ Branch_Id ┆ Payment_Id ┆ Date       ┆ Visit_Time ┆ Updated_At │
│ ---      ┆ ---         ┆ ---     ┆ ---       ┆ ---        ┆ ---        ┆ ---        ┆ ---        │
│ i64      ┆ i64         ┆ i64     ┆ i8        ┆ str        ┆ date       ┆ datetime[μ ┆ datetime[μ │
│          ┆             ┆         ┆           ┆            ┆            ┆ s]         ┆ s]         │
╞══════════╪═════════════╪═════════╪═══════════╪════════════╪════════════╪════════════╪════════════╡
│ 4        ┆ 4           ┆ 1       ┆ 1         ┆ 4-1        ┆ 2026-01-02 ┆ 2026-01-02 ┆ 2026-01-02 │
│          ┆             ┆         ┆           ┆            ┆            ┆ 19:23:07   ┆ 19:23:07   │
│ 13       ┆ 4           ┆ 1       ┆ 1         ┆ 4-2        ┆ 2026-01-03 ┆ 2026-01-03 ┆ 2026-01-03 │
│          ┆             ┆         ┆           ┆            ┆            ┆ 14:23:42   ┆ 14:23:42   │
│ 18       ┆ 4           ┆ 1       ┆ 1         ┆ 4-3        ┆ 2026-01-05 ┆ 2026-01-05 ┆ 2026-01-05 │
│          ┆             ┆         ┆           ┆            ┆            ┆ 07:32:18   ┆ 07:32:18   │
│ 21       ┆ 4           ┆ 1       ┆ 1         ┆ 4-4        ┆ 2026-01-06 ┆ 2026-01-06 ┆ 2026-01-06 │
│          ┆             ┆         ┆           ┆            ┆            ┆ 18:09:03   ┆ 18:09:03   │
│ 36       ┆ 4           ┆ 1       ┆ 1         ┆ 4-5        ┆ 2026-01-12 ┆ 2026-01-12 ┆ 2026-01-12 │
│          ┆             ┆         ┆           ┆            ┆            ┆ 16:42:15   ┆ 16:42:15   │
│ …        ┆ …           ┆ …       ┆ …         ┆ …          ┆ …          ┆ …          ┆ …          │
│ 2219     ┆ 4           ┆ 3       ┆ 1         ┆ 4-24       ┆ 2026-05-08 ┆ 2026-05-08 ┆ 2026-05-08 │
│          ┆             ┆         ┆           ┆            ┆            ┆ 09:13:25   ┆ 09:13:25   │
│ 2260     ┆ 4           ┆ 3       ┆ 1         ┆ 4-24       ┆ 2026-05-11 ┆ 2026-05-11 ┆ 2026-05-11 │
│          ┆             ┆         ┆           ┆            ┆            ┆ 13:00:32   ┆ 13:00:32   │
│ 2270     ┆ 4           ┆ 3       ┆ 1         ┆ 4-24       ┆ 2026-05-12 ┆ 2026-05-12 ┆ 2026-05-12 │
│          ┆             ┆         ┆           ┆            ┆            ┆ 10:46:17   ┆ 10:46:17   │
│ 2352     ┆ 4           ┆ 3       ┆ 1         ┆ 4-24       ┆ 2026-05-18 ┆ 2026-05-18 ┆ 2026-05-18 │
│          ┆             ┆         ┆           ┆            ┆            ┆ 16:08:10   ┆ 16:08:10   │
│ 2532     ┆ 4           ┆ 3       ┆ 1         ┆ 4-24       ┆ 2026-05-30 ┆ 2026-05-30 ┆ 2026-05-30 │
│          ┆             ┆         ┆           ┆            ┆            ┆ 20:50:38   ┆ 20:50:38   │
└──────────┴─────────────┴─────────┴───────────┴────────────┴────────────┴────────────┴────────────┘

In [17]:
datasets[2].group_by("Customer_Id", "Plan_Id").len().sort(by = "len", descending=True)

shape: (270, 3)
┌─────────────┬─────────┬─────┐
│ Customer_Id ┆ Plan_Id ┆ len │
│ ---         ┆ ---     ┆ --- │
│ i64         ┆ i64     ┆ u32 │
╞═════════════╪═════════╪═════╡
│ 29          ┆ 3       ┆ 45  │
│ 11          ┆ 4       ┆ 42  │
│ 18          ┆ 4       ┆ 40  │
│ 9           ┆ 3       ┆ 36  │
│ 48          ┆ 1       ┆ 35  │
│ …           ┆ …       ┆ …   │
│ 91          ┆ 1       ┆ 1   │
│ 49          ┆ 3       ┆ 1   │
│ 98          ┆ 1       ┆ 1   │
│ 86          ┆ 1       ┆ 1   │
│ 67          ┆ 1       ┆ 1   │
└─────────────┴─────────┴─────┘