In [1]:
import polars as pl
import numpy as np

In [31]:
df = pl.read_csv("./customers.csv")
df.head(3)

shape: (3, 9)
┌────────────┬────────────┬────────┬────────────┬───┬────────────┬─────────┬───────────┬───────────┐
│ Name       ┆ Last_Name  ┆ Gender ┆ Birth_Date ┆ … ┆ Longitude  ┆ Zipcode ┆ Email     ┆ Phone_Num │
│ ---        ┆ ---        ┆ ---    ┆ ---        ┆   ┆ ---        ┆ ---     ┆ ---       ┆ ber       │
│ str        ┆ str        ┆ bool   ┆ str        ┆   ┆ f64        ┆ i64     ┆ str       ┆ ---       │
│            ┆            ┆        ┆            ┆   ┆            ┆         ┆           ┆ str       │
╞════════════╪════════════╪════════╪════════════╪═══╪════════════╪═════════╪═══════════╪═══════════╡
│ Frida      ┆ Esquibel   ┆ false  ┆ 1992-02-13 ┆ … ┆ -101.29587 ┆ 36256   ┆ o******** ┆ (473)5353 │
│ Gabriela   ┆ Hinojosa   ┆        ┆ T00:00:00. ┆   ┆            ┆         ┆ *****j@ho ┆ 482       │
│            ┆            ┆        ┆ 000000     ┆   ┆            ┆         ┆ tmail.com ┆           │
│ Soledad    ┆ Cintrón    ┆ false  ┆ 2001-11-28 ┆ … ┆ -101.30515 ┆ 36263   ┆ y******** ┆ (473)7706 │
│ Adriana    ┆ Aragón     ┆        ┆ T00:00:00. ┆   ┆            ┆         ┆ **j@gmail ┆ 836       │
│            ┆            ┆        ┆ 000000     ┆   ┆            ┆         ┆ .com      ┆           │
│ Gerardo    ┆ Téllez de  ┆ true   ┆ 1993-08-27 ┆ … ┆ -101.29672 ┆ 36253   ┆ q******** ┆ (473)1254 │
│ Clemente   ┆ la Rosa    ┆        ┆ T00:00:00. ┆   ┆            ┆         ┆ ****r@gma ┆ 092       │
│            ┆            ┆        ┆ 000000     ┆   ┆            ┆         ┆ il.com    ┆           │
└────────────┴────────────┴────────┴────────────┴───┴────────────┴─────────┴───────────┴───────────┘

In [28]:
gym_hours = {"open" : "6.0",
             "close" : "22.0"}

profiles = {
"1": {
"name" : "frequent_morning",
"days_probability" : {"mon": {"day_number" : 1, "day_name" : "Monday", "day_weight" : .89},
                      "tue": {"day_number" : 2, "day_name" : "Tuesday", "day_weight" : .76},
                      "wed": {"day_number" : 3, "day_name" : "Wednesday", "day_weight" : .85},
                      "thu": {"day_number" : 4, "day_name" : "Thursday", "day_weight" : .7},
                      "fri": {"day_number" : 5, "day_name" : "Friday", "day_weight" :.9},
                      "sat": {"day_number" : 6, "day_name" : "Saturday", "day_weight" : .9},
                      "sun": {"day_number" : 7, "day_name" : "Sunday", "day_weight" : 0}
},
"hour_mean" : "6.43",
"hour_mean" : ".75"
},
"2" : {
"name" : "frequent_noon",
"days_probability" : {"mon": {"day_number" : 1, "day_name" : "Monday", "day_weight" : .7},
                      "tue": {"day_number" : 2, "day_name" : "Tuesday", "day_weight" : .82},
                      "wed": {"day_number" : 3, "day_name" : "Wednesday", "day_weight" : .67},
                      "thu": {"day_number" : 4, "day_name" : "Thursday", "day_weight" : .87},
                      "fri": {"day_number" : 5, "day_name" : "Friday", "day_weight" :.78},
                      "sat": {"day_number" : 6, "day_name" : "Saturday", "day_weight" : .84},
                      "sun": {"day_number" : 7, "day_name" : "Sunday", "day_weight" : 0}
},
"hour_mean" : "13.16",
"hour_mean" : "1.40"
            },
"3" :{
"name" : "frequent_night",
"days_probability" : {"mon": {"day_number" : 1, "day_name" : "Monday", "day_weight" : .74},
                      "tue": {"day_number" : 2, "day_name" : "Tuesday", "day_weight" : .87},
                      "wed": {"day_number" : 3, "day_name" : "Wednesday", "day_weight" : .76},
                      "thu": {"day_number" : 4, "day_name" : "Thursday", "day_weight" : .84},
                      "fri": {"day_number" : 5, "day_name" : "Friday", "day_weight" :.4},
                      "sat": {"day_number" : 6, "day_name" : "Saturday", "day_weight" : .8},
                      "sun": {"day_number" : 7, "day_name" : "Sunday", "day_weight" : 0}
},
"hour_mean" : "19.5",
"hour_mean" : "1.15"
},
"4" :{
"name" : "random_morning",
"days_probability" : {"mon": {"day_number" : 1, "day_name" : "Monday", "day_weight" : .74},
                      "tue": {"day_number" : 2, "day_name" : "Tuesday", "day_weight" : .83},
                      "wed": {"day_number" : 3, "day_name" : "Wednesday", "day_weight" : .68},
                      "thu": {"day_number" : 4, "day_name" : "Thursday", "day_weight" : 0.86},
                      "fri": {"day_number" : 5, "day_name" : "Friday", "day_weight" :.4},
                      "sat": {"day_number" : 6, "day_name" : "Saturday", "day_weight" : .8},
                      "sun": {"day_number" : 7, "day_name" : "Sunday", "day_weight" : 0}
},
"hour_mean" : "8.5",
"hour_mean" : "2.05"
},
"5" :{
"name" : "random_night",
"days_probability" : {"mon": {"day_number" : 1, "day_name" : "Monday", "day_weight" : .8},
                      "tue": {"day_number" : 2, "day_name" : "Tuesday", "day_weight" : 1},
                      "wed": {"day_number" : 3, "day_name" : "Wednesday", "day_weight" : .8},
                      "thu": {"day_number" : 4, "day_name" : "Thursday", "day_weight" : 1},
                      "fri": {"day_number" : 5, "day_name" : "Friday", "day_weight" :.4},
                      "sat": {"day_number" : 6, "day_name" : "Saturday", "day_weight" : .8},
                      "sun": {"day_number" : 7, "day_name" : "Sunday", "day_weight" : 0}
},
"hour_mean" : "20.1",
"hour_mean" : "2.08"
},
"6" :{
"name" : "full_random",
"days_probability" : {"mon": {"day_number" : 1, "day_name" : "Monday", "day_weight" : .5},
                      "tue": {"day_number" : 2, "day_name" : "Tuesday", "day_weight" : .5},
                      "wed": {"day_number" : 3, "day_name" : "Wednesday", "day_weight" : .5},
                      "thu": {"day_number" : 4, "day_name" : "Thursday", "day_weight" : 5},
                      "fri": {"day_number" : 5, "day_name" : "Friday", "day_weight" :.5},
                      "sat": {"day_number" : 6, "day_name" : "Saturday", "day_weight" : .5},
                      "sun": {"day_number" : 7, "day_name" : "Sunday", "day_weight" : 0}
},
"hour_mean" : "14.00",
"hour_mean" : "3.0"
},
"7" :{
"name" : "rare_random",
"days_probability" : {"mon": {"day_number" : 1, "day_name" : "Monday", "day_weight" : .2},
                      "tue": {"day_number" : 2, "day_name" : "Tuesday", "day_weight" : .2},
                      "wed": {"day_number" : 3, "day_name" : "Wednesday", "day_weight" : .4},
                      "thu": {"day_number" : 4, "day_name" : "Thursday", "day_weight" : .2},
                      "fri": {"day_number" : 5, "day_name" : "Friday", "day_weight" :.3},
                      "sat": {"day_number" : 6, "day_name" : "Saturday", "day_weight" : .4},
                      "sun": {"day_number" : 7, "day_name" : "Sunday", "day_weight" : 0}
},
"hour_mean" : "16.0",
"hour_mean" : "3.5"
},
"8" :{
"name" : "ultrarare_random",
"days_probability" : {"mon": {"day_number" : 1, "day_name" : "Monday", "day_weight" : .1},
                      "tue": {"day_number" : 2, "day_name" : "Tuesday", "day_weight" : .2},
                      "wed": {"day_number" : 3, "day_name" : "Wednesday", "day_weight" : .1},
                      "thu": {"day_number" : 4, "day_name" : "Thursday", "day_weight" : .1},
                      "fri": {"day_number" : 5, "day_name" : "Friday", "day_weight" :.2},
                      "sat": {"day_number" : 6, "day_name" : "Saturday", "day_weight" : .3},
                      "sun": {"day_number" : 7, "day_name" : "Sunday", "day_weight" : 0}
},
"hour_mean" : "14.5",
"hour_mean" : "5.5"
}
}

profile_weights = {"1" : 0.23076923, "2": 0.12820513, "3" : 0.25641026, "4" : 0.07692308, "5" : 0.07692308, "6" : 0.05128205, "7" : 0.07692308, "8" : 0.1025641}

In [ ]:
# Functions
def create_customer_profiles(profile_weights_ : dict, n_):
    return {i: int(np.random.choice(list(profile_weights.keys()), p = list(profile_weights.values()))) for i in range(n_) }

In [29]:
# prob = np.array((.9,0.5,1,.3,.3,.2,.3,.4))

# prob/sum(prob)

{0: 5,
 1: 2,
 2: 6,
 3: 8,
 4: 3,
 5: 3,
 6: 8,
 7: 3,
 8: 1,
 9: 7,
 10: 2,
 11: 3,
 12: 2,
 13: 1,
 14: 8,
 15: 3,
 16: 8,
 17: 3,
 18: 4,
 19: 3,
 20: 3,
 21: 3,
 22: 2,
 23: 7,
 24: 7,
 25: 3,
 26: 1,
 27: 3,
 28: 4,
 29: 3,
 30: 1,
 31: 6,
 32: 3,
 33: 8,
 34: 4,
 35: 1,
 36: 3,
 37: 5,
 38: 3,
 39: 2,
 40: 1,
 41: 5,
 42: 1,
 43: 5,
 44: 8,
 45: 3,
 46: 5,
 47: 8,
 48: 1,
 49: 1,
 50: 1,
 51: 3,
 52: 8,
 53: 1,
 54: 5,
 55: 8,
 56: 1,
 57: 4}

In [ ]:

customer_profiles 
df_cleaned = df.with_columns(pl.row_index().alias("Aux"),
                             pl.lit("Active").alias("Status"))
df_cleaned

shape: (58, 9)
┌────────────┬────────────┬────────┬────────────┬───┬────────────┬─────────┬───────────┬───────────┐
│ Name       ┆ Last_Name  ┆ Gender ┆ Birth_Date ┆ … ┆ Longitude  ┆ Zipcode ┆ Email     ┆ Phone_Num │
│ ---        ┆ ---        ┆ ---    ┆ ---        ┆   ┆ ---        ┆ ---     ┆ ---       ┆ ber       │
│ str        ┆ str        ┆ bool   ┆ str        ┆   ┆ f64        ┆ i64     ┆ str       ┆ ---       │
│            ┆            ┆        ┆            ┆   ┆            ┆         ┆           ┆ str       │
╞════════════╪════════════╪════════╪════════════╪═══╪════════════╪═════════╪═══════════╪═══════════╡
│ Frida      ┆ Esquibel   ┆ false  ┆ 1992-02-13 ┆ … ┆ -101.29587 ┆ 36256   ┆ o******** ┆ (473)5353 │
│ Gabriela   ┆ Hinojosa   ┆        ┆ T00:00:00. ┆   ┆            ┆         ┆ *****j@ho ┆ 482       │
│            ┆            ┆        ┆ 000000     ┆   ┆            ┆         ┆ tmail.com ┆           │
│ Soledad    ┆ Cintrón    ┆ false  ┆ 2001-11-28 ┆ … ┆ -101.30515 ┆ 36263   ┆ y******** ┆ (473)7706 │
│ Adriana    ┆ Aragón     ┆        ┆ T00:00:00. ┆   ┆            ┆         ┆ **j@gmail ┆ 836       │
│            ┆            ┆        ┆ 000000     ┆   ┆            ┆         ┆ .com      ┆           │
│ Gerardo    ┆ Téllez de  ┆ true   ┆ 1993-08-27 ┆ … ┆ -101.29672 ┆ 36253   ┆ q******** ┆ (473)1254 │
│ Clemente   ┆ la Rosa    ┆        ┆ T00:00:00. ┆   ┆            ┆         ┆ ****r@gma ┆ 092       │
│            ┆            ┆        ┆ 000000     ┆   ┆            ┆         ┆ il.com    ┆           │
│ José María ┆ Manzanares ┆ true   ┆ 1984-04-15 ┆ … ┆ -101.26808 ┆ 36053   ┆ s******** ┆ (473)7592 │
│            ┆ Uribe      ┆        ┆ T00:00:00. ┆   ┆            ┆         ┆ *****v@gm ┆ 128       │
│            ┆            ┆        ┆ 000000     ┆   ┆            ┆         ┆ ail.com   ┆           │
│ Tomás José ┆ Aguilera   ┆ true   ┆ 2001-11-08 ┆ … ┆ -101.26226 ┆ 36255   ┆ n******** ┆ (473)7118 │
│            ┆ Tejeda     ┆        ┆ T00:00:00. ┆   ┆            ┆         ┆ *e@hotmai ┆ 719       │
│            ┆            ┆        ┆ 000000     ┆   ┆            ┆         ┆ l.com     ┆           │
│ …          ┆ …          ┆ …      ┆ …          ┆ … ┆ …          ┆ …       ┆ …         ┆ …         │
│ Concepción ┆ Salazar    ┆ false  ┆ 2000-05-20 ┆ … ┆ -101.29572 ┆ 36257   ┆ j******** ┆ (473)8696 │
│ Eugenia    ┆ Molina     ┆        ┆ T00:00:00. ┆   ┆            ┆         ┆ ********v ┆ 573       │
│            ┆            ┆        ┆ 000000     ┆   ┆            ┆         ┆ @gmail.co ┆           │
│            ┆            ┆        ┆            ┆   ┆            ┆         ┆ m         ┆           │
│ Federico   ┆ Vera Muñiz ┆ true   ┆ 2000-11-16 ┆ … ┆ -101.26652 ┆ 36259   ┆ i******** ┆ (473)9342 │
│ Rufino     ┆            ┆        ┆ T00:00:00. ┆   ┆ 5          ┆         ┆ ****f@hot ┆ 285       │
│            ┆            ┆        ┆ 000000     ┆   ┆            ┆         ┆ mail.com  ┆           │
│ Ariadna    ┆ Bañuelos   ┆ false  ┆ 1985-04-26 ┆ … ┆ -101.28499 ┆ 36251   ┆ k******** ┆ (473)8088 │
│ Esparta    ┆ Guevara    ┆        ┆ T00:00:00. ┆   ┆            ┆         ┆ **a@gmail ┆ 412       │
│            ┆            ┆        ┆ 000000     ┆   ┆            ┆         ┆ .com      ┆           │
│ Norma      ┆ Casas      ┆ false  ┆ 1985-05-14 ┆ … ┆ -101.27624 ┆ 36053   ┆ b******** ┆ (473)4765 │
│ Isabela    ┆ García     ┆        ┆ T00:00:00. ┆   ┆ 5          ┆         ┆ *******n@ ┆ 931       │
│            ┆            ┆        ┆ 000000     ┆   ┆            ┆         ┆ hotmail.c ┆           │
│            ┆            ┆        ┆            ┆   ┆            ┆         ┆ om        ┆           │
│ Felix      ┆ Sepúlveda  ┆ true   ┆ 2001-02-04 ┆ … ┆ -101.29833 ┆ 36253   ┆ g******** ┆ (473)4454 │
│ Cristian   ┆ Molina     ┆        ┆ T00:00:00. ┆   ┆            ┆         ┆ *r@hotmai ┆ 286       │
│            ┆            ┆        ┆ 000000     ┆   ┆            ┆         ┆ l.com     ┆           │
└────────────┴────────────┴────────┴────────────┴───┴────────────┴─────────┴───────────┴───────────┘